//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.27 at 04:27:20 PM EEST 
//


package com.thomascook.content.common;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for MediaType complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="MediaType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="URI" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="Title" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AltText" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Type" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="video/mp4"/>
 *             &lt;enumeration value="image/png"/>
 *             &lt;enumeration value="image/jpeg"/>
 *             &lt;enumeration value="image/360view"/>
 *             &lt;enumeration value="video/heliview"/>
 *             &lt;enumeration value="image/seal"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="DisplaySequence" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="Primary" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="DisplayInMainViewer" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="ImageType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MediaType", propOrder = {
        "uri",
        "title",
        "altText"
})
public class MediaType {

    @XmlElement(name = "URI", required = true)
    @XmlSchemaType(name = "anyURI")
    private String uri;
    @XmlElement(name = "Title")
    private String title;
    @XmlElement(name = "AltText")
    private String altText;
    @XmlAttribute(name = "Type", required = true)
    private String type;
    @XmlAttribute(name = "DisplaySequence")
    private Integer displaySequence;
    @XmlAttribute(name = "Primary")
    private Boolean primary;
    @XmlAttribute(name = "DisplayInMainViewer")
    private Boolean displayInMainViewer;
    @XmlAttribute(name = "ImageType")
    private String imageType;

    /**
     * Gets the value of the uri property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getURI() {
        return uri;
    }

    /**
     * Sets the value of the uri property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setURI(String value) {
        this.uri = value;
    }

    /**
     * Gets the value of the title property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the altText property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getAltText() {
        return altText;
    }

    /**
     * Sets the value of the altText property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAltText(String value) {
        this.altText = value;
    }

    /**
     * Gets the value of the type property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the displaySequence property.
     *
     * @return possible object is
     * {@link Integer }
     */
    public Integer getDisplaySequence() {
        return displaySequence;
    }

    /**
     * Sets the value of the displaySequence property.
     *
     * @param value allowed object is
     *              {@link Integer }
     */
    public void setDisplaySequence(Integer value) {
        this.displaySequence = value;
    }

    /**
     * Gets the value of the primary property.
     *
     * @return possible object is
     * {@link Boolean }
     */
    public Boolean isPrimary() {
        return primary;
    }

    /**
     * Sets the value of the primary property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setPrimary(Boolean value) {
        this.primary = value;
    }

    /**
     * Gets the value of the displayInMainViewer property.
     *
     * @return possible object is
     * {@link Boolean }
     */
    public Boolean isDisplayInMainViewer() {
        return displayInMainViewer;
    }

    /**
     * Sets the value of the displayInMainViewer property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setDisplayInMainViewer(Boolean value) {
        this.displayInMainViewer = value;
    }

    /**
     * Gets the value of the imageType property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getImageType() {
        return imageType;
    }

    /**
     * Sets the value of the imageType property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setImageType(String value) {
        this.imageType = value;
    }

}
