//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.27 at 04:27:20 PM EEST 
//


package com.thomascook.content.generichighlight;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for GenericHighlightType complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="GenericHighlightType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="Type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Logo" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Sequence" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GenericHighlightType")
@XmlSeeAlso({
        com.thomascook.content.concept.Concept.Value.class,
        com.thomascook.content.highlightedfeature.HighlightedFeature.Value.class,
        com.thomascook.content.theme.Theme.Value.class
})
public class GenericHighlightType {

    @XmlAttribute(name = "Type")
    private String type;
    @XmlAttribute(name = "Logo")
    private String logo;
    @XmlAttribute(name = "Sequence")
    private Integer sequence;

    /**
     * Gets the value of the type property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the logo property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getLogo() {
        return logo;
    }

    /**
     * Sets the value of the logo property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setLogo(String value) {
        this.logo = value;
    }

    /**
     * Gets the value of the sequence property.
     *
     * @return possible object is
     * {@link Integer }
     */
    public Integer getSequence() {
        return sequence;
    }

    /**
     * Sets the value of the sequence property.
     *
     * @param value allowed object is
     *              {@link Integer }
     */
    public void setSequence(Integer value) {
        this.sequence = value;
    }

}
