//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.30 at 05:53:57 PM EEST 
//


package com.thomascook.toscaBookAdapter.request;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="POS" type="{http://www.opentravel.org/OTA/2003/05}POS_Type" minOccurs="0"/>
 *         &lt;element name="UniqueID" type="{http://www.opentravel.org/OTA/2003/05}UniqueID_Type" minOccurs="0"/>
 *         &lt;element name="PackageRequest" type="{http://www.opentravel.org/OTA/2003/05}PackageType" minOccurs="0"/>
 *         &lt;element name="ContactDetail" type="{http://www.opentravel.org/OTA/2003/05}ContactPersonType" minOccurs="0"/>
 *         &lt;element name="PassengerListItems" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="PassengerListItem" type="{http://www.opentravel.org/OTA/2003/05}PkgPassengerListItem" maxOccurs="99"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="OwnInsuranceChoices" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="OwnInsuranceChoice" type="{http://www.opentravel.org/OTA/2003/05}OwnInsuranceChoiceType" maxOccurs="9"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="PaymentDetails" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="PaymentDetail" maxOccurs="9">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;extension base="{http://www.opentravel.org/OTA/2003/05}PaymentDetailType">
 *                           &lt;attribute name="SecurityCode" type="{http://www.opentravel.org/OTA/2003/05}Numeric1to9999" />
 *                         &lt;/extension>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{http://www.opentravel.org/OTA/2003/05}TPA_Extensions" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.opentravel.org/OTA/2003/05}ReqRespVersion"/>
 *       &lt;attGroup ref="{http://www.opentravel.org/OTA/2003/05}OTA_PayloadStdAttributes"/>
 *       &lt;attribute name="ActionType" use="required" type="{http://www.opentravel.org/OTA/2003/05}TransactionActionType" />
 *       &lt;attribute name="ExpectedGrossAmount" type="{http://www.opentravel.org/OTA/2003/05}Money" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "pos",
        "uniqueID",
        "packageRequest",
        "contactDetail",
        "passengerListItems",
        "ownInsuranceChoices",
        "paymentDetails",
        "tpaExtensions"
})
@XmlRootElement(name = "OTA_PkgBookRQ")
public class OTAPkgBookRQ {

    @XmlElement(name = "POS")
    private POSType pos;
    @XmlElement(name = "UniqueID")
    private UniqueIDType uniqueID;
    @XmlElement(name = "PackageRequest")
    private PackageType packageRequest;
    @XmlElement(name = "ContactDetail")
    private ContactPersonType contactDetail;
    @XmlElement(name = "PassengerListItems")
    private PassengerListItems passengerListItems;
    @XmlElement(name = "OwnInsuranceChoices")
    private OwnInsuranceChoices ownInsuranceChoices;
    @XmlElement(name = "PaymentDetails")
    private PaymentDetails paymentDetails;
    @XmlElement(name = "TPA_Extensions")
    private TPAExtensionsType tpaExtensions;
    @XmlAttribute(name = "ActionType", required = true)
    private TransactionActionType actionType;
    @XmlAttribute(name = "ExpectedGrossAmount")
    private BigDecimal expectedGrossAmount;
    @XmlAttribute(name = "ReqRespVersion")
    private String reqRespVersion;
    @XmlAttribute(name = "EchoToken")
    private String echoToken;
    @XmlAttribute(name = "TimeStamp")
    @XmlSchemaType(name = "dateTime")
    private XMLGregorianCalendar timeStamp;
    @XmlAttribute(name = "Target")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    private String target;
    @XmlAttribute(name = "Version")
    private BigDecimal version;
    @XmlAttribute(name = "TransactionIdentifier")
    private String transactionIdentifier;
    @XmlAttribute(name = "SequenceNmbr")
    @XmlSchemaType(name = "nonNegativeInteger")
    private BigInteger sequenceNmbr;
    @XmlAttribute(name = "TransactionStatusCode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    private String transactionStatusCode;
    @XmlAttribute(name = "RetransmissionIndicator")
    private Boolean retransmissionIndicator;
    @XmlAttribute(name = "PrimaryLangID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "language")
    private String primaryLangID;
    @XmlAttribute(name = "AltLangID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "language")
    private String altLangID;

    /**
     * Gets the value of the pos property.
     *
     * @return possible object is
     * {@link POSType }
     */
    public POSType getPOS() {
        return pos;
    }

    /**
     * Sets the value of the pos property.
     *
     * @param value allowed object is
     *              {@link POSType }
     */
    public void setPOS(POSType value) {
        this.pos = value;
    }

    /**
     * Gets the value of the uniqueID property.
     *
     * @return possible object is
     * {@link UniqueIDType }
     */
    public UniqueIDType getUniqueID() {
        return uniqueID;
    }

    /**
     * Sets the value of the uniqueID property.
     *
     * @param value allowed object is
     *              {@link UniqueIDType }
     */
    public void setUniqueID(UniqueIDType value) {
        this.uniqueID = value;
    }

    /**
     * Gets the value of the packageRequest property.
     *
     * @return possible object is
     * {@link PackageType }
     */
    public PackageType getPackageRequest() {
        return packageRequest;
    }

    /**
     * Sets the value of the packageRequest property.
     *
     * @param value allowed object is
     *              {@link PackageType }
     */
    public void setPackageRequest(PackageType value) {
        this.packageRequest = value;
    }

    /**
     * Gets the value of the contactDetail property.
     *
     * @return possible object is
     * {@link ContactPersonType }
     */
    public ContactPersonType getContactDetail() {
        return contactDetail;
    }

    /**
     * Sets the value of the contactDetail property.
     *
     * @param value allowed object is
     *              {@link ContactPersonType }
     */
    public void setContactDetail(ContactPersonType value) {
        this.contactDetail = value;
    }

    /**
     * Gets the value of the passengerListItems property.
     *
     * @return possible object is
     * {@link PassengerListItems }
     */
    public PassengerListItems getPassengerListItems() {
        return passengerListItems;
    }

    /**
     * Sets the value of the passengerListItems property.
     *
     * @param value allowed object is
     *              {@link PassengerListItems }
     */
    public void setPassengerListItems(PassengerListItems value) {
        this.passengerListItems = value;
    }

    /**
     * Gets the value of the ownInsuranceChoices property.
     *
     * @return possible object is
     * {@link OwnInsuranceChoices }
     */
    public OwnInsuranceChoices getOwnInsuranceChoices() {
        return ownInsuranceChoices;
    }

    /**
     * Sets the value of the ownInsuranceChoices property.
     *
     * @param value allowed object is
     *              {@link OwnInsuranceChoices }
     */
    public void setOwnInsuranceChoices(OwnInsuranceChoices value) {
        this.ownInsuranceChoices = value;
    }

    /**
     * Gets the value of the paymentDetails property.
     *
     * @return possible object is
     * {@link PaymentDetails }
     */
    public PaymentDetails getPaymentDetails() {
        return paymentDetails;
    }

    /**
     * Sets the value of the paymentDetails property.
     *
     * @param value allowed object is
     *              {@link PaymentDetails }
     */
    public void setPaymentDetails(PaymentDetails value) {
        this.paymentDetails = value;
    }

    /**
     * Gets the value of the tpaExtensions property.
     *
     * @return possible object is
     * {@link TPAExtensionsType }
     */
    public TPAExtensionsType getTPAExtensions() {
        return tpaExtensions;
    }

    /**
     * Sets the value of the tpaExtensions property.
     *
     * @param value allowed object is
     *              {@link TPAExtensionsType }
     */
    public void setTPAExtensions(TPAExtensionsType value) {
        this.tpaExtensions = value;
    }

    /**
     * Gets the value of the actionType property.
     *
     * @return possible object is
     * {@link TransactionActionType }
     */
    public TransactionActionType getActionType() {
        return actionType;
    }

    /**
     * Sets the value of the actionType property.
     *
     * @param value allowed object is
     *              {@link TransactionActionType }
     */
    public void setActionType(TransactionActionType value) {
        this.actionType = value;
    }

    /**
     * Gets the value of the expectedGrossAmount property.
     *
     * @return possible object is
     * {@link BigDecimal }
     */
    public BigDecimal getExpectedGrossAmount() {
        return expectedGrossAmount;
    }

    /**
     * Sets the value of the expectedGrossAmount property.
     *
     * @param value allowed object is
     *              {@link BigDecimal }
     */
    public void setExpectedGrossAmount(BigDecimal value) {
        this.expectedGrossAmount = value;
    }

    /**
     * Gets the value of the reqRespVersion property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getReqRespVersion() {
        return reqRespVersion;
    }

    /**
     * Sets the value of the reqRespVersion property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setReqRespVersion(String value) {
        this.reqRespVersion = value;
    }

    /**
     * Gets the value of the echoToken property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getEchoToken() {
        return echoToken;
    }

    /**
     * Sets the value of the echoToken property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setEchoToken(String value) {
        this.echoToken = value;
    }

    /**
     * Gets the value of the timeStamp property.
     *
     * @return possible object is
     * {@link XMLGregorianCalendar }
     */
    public XMLGregorianCalendar getTimeStamp() {
        return timeStamp;
    }

    /**
     * Sets the value of the timeStamp property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     */
    public void setTimeStamp(XMLGregorianCalendar value) {
        this.timeStamp = value;
    }

    /**
     * Gets the value of the target property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getTarget() {
        if (target == null) {
            return "Production";
        } else {
            return target;
        }
    }

    /**
     * Sets the value of the target property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setTarget(String value) {
        this.target = value;
    }

    /**
     * Gets the value of the version property.
     *
     * @return possible object is
     * {@link BigDecimal }
     */
    public BigDecimal getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     *
     * @param value allowed object is
     *              {@link BigDecimal }
     */
    public void setVersion(BigDecimal value) {
        this.version = value;
    }

    /**
     * Gets the value of the transactionIdentifier property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getTransactionIdentifier() {
        return transactionIdentifier;
    }

    /**
     * Sets the value of the transactionIdentifier property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setTransactionIdentifier(String value) {
        this.transactionIdentifier = value;
    }

    /**
     * Gets the value of the sequenceNmbr property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    public BigInteger getSequenceNmbr() {
        return sequenceNmbr;
    }

    /**
     * Sets the value of the sequenceNmbr property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setSequenceNmbr(BigInteger value) {
        this.sequenceNmbr = value;
    }

    /**
     * Gets the value of the transactionStatusCode property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getTransactionStatusCode() {
        return transactionStatusCode;
    }

    /**
     * Sets the value of the transactionStatusCode property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setTransactionStatusCode(String value) {
        this.transactionStatusCode = value;
    }

    /**
     * Gets the value of the retransmissionIndicator property.
     *
     * @return possible object is
     * {@link Boolean }
     */
    public Boolean isRetransmissionIndicator() {
        return retransmissionIndicator;
    }

    /**
     * Sets the value of the retransmissionIndicator property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setRetransmissionIndicator(Boolean value) {
        this.retransmissionIndicator = value;
    }

    /**
     * Gets the value of the primaryLangID property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPrimaryLangID() {
        return primaryLangID;
    }

    /**
     * Sets the value of the primaryLangID property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPrimaryLangID(String value) {
        this.primaryLangID = value;
    }

    /**
     * Gets the value of the altLangID property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getAltLangID() {
        return altLangID;
    }

    /**
     * Sets the value of the altLangID property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAltLangID(String value) {
        this.altLangID = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * <p>
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="OwnInsuranceChoice" type="{http://www.opentravel.org/OTA/2003/05}OwnInsuranceChoiceType" maxOccurs="9"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "ownInsuranceChoice"
    })
    public static class OwnInsuranceChoices {

        @XmlElement(name = "OwnInsuranceChoice", required = true)
        List<OwnInsuranceChoiceType> ownInsuranceChoice;

        /**
         * Gets the value of the ownInsuranceChoice property.
         * <p>
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the ownInsuranceChoice property.
         * <p>
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getOwnInsuranceChoice().add(newItem);
         * </pre>
         * <p>
         * <p>
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link OwnInsuranceChoiceType }
         */
        public List<OwnInsuranceChoiceType> getOwnInsuranceChoice() {
            if (ownInsuranceChoice == null) {
                ownInsuranceChoice = new ArrayList<>();
            }
            return this.ownInsuranceChoice;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * <p>
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="PassengerListItem" type="{http://www.opentravel.org/OTA/2003/05}PkgPassengerListItem" maxOccurs="99"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "passengerListItem"
    })
    public static class PassengerListItems {

        @XmlElement(name = "PassengerListItem", required = true)
        List<PkgPassengerListItem> passengerListItem;

        /**
         * Gets the value of the passengerListItem property.
         * <p>
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the passengerListItem property.
         * <p>
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPassengerListItem().add(newItem);
         * </pre>
         * <p>
         * <p>
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PkgPassengerListItem }
         */
        public List<PkgPassengerListItem> getPassengerListItem() {
            if (passengerListItem == null) {
                passengerListItem = new ArrayList<>();
            }
            return this.passengerListItem;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * <p>
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="PaymentDetail" maxOccurs="9">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;extension base="{http://www.opentravel.org/OTA/2003/05}PaymentDetailType">
     *                 &lt;attribute name="SecurityCode" type="{http://www.opentravel.org/OTA/2003/05}Numeric1to9999" />
     *               &lt;/extension>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "paymentDetail"
    })
    public static class PaymentDetails {

        @XmlElement(name = "PaymentDetail", required = true)
        List<PaymentDetail> paymentDetail;

        /**
         * Gets the value of the paymentDetail property.
         * <p>
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the paymentDetail property.
         * <p>
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPaymentDetail().add(newItem);
         * </pre>
         * <p>
         * <p>
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PaymentDetail }
         */
        public List<PaymentDetail> getPaymentDetail() {
            if (paymentDetail == null) {
                paymentDetail = new ArrayList<>();
            }
            return this.paymentDetail;
        }


        /**
         * <p>Java class for anonymous complex type.
         * <p>
         * <p>The following schema fragment specifies the expected content contained within this class.
         * <p>
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;extension base="{http://www.opentravel.org/OTA/2003/05}PaymentDetailType">
         *       &lt;attribute name="SecurityCode" type="{http://www.opentravel.org/OTA/2003/05}Numeric1to9999" />
         *     &lt;/extension>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class PaymentDetail
                extends PaymentDetailType {

            @XmlAttribute(name = "SecurityCode")
            Integer securityCode;

            /**
             * Gets the value of the securityCode property.
             *
             * @return possible object is
             * {@link Integer }
             */
            public Integer getSecurityCode() {
                return securityCode;
            }

            /**
             * Sets the value of the securityCode property.
             *
             * @param value allowed object is
             *              {@link Integer }
             */
            public void setSecurityCode(Integer value) {
                this.securityCode = value;
            }

        }

    }

}
