//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.30 at 05:53:57 PM EEST 
//


package com.thomascook.toscaBookAdapter.request;

import javax.xml.bind.annotation.*;


/**
 * Details of the customer's own insurance policy.
 * <p>
 * <p>Java class for OwnInsuranceChoiceType complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="OwnInsuranceChoiceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CustomerCounts" type="{http://www.opentravel.org/OTA/2003/05}CustomerCountsType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="RPH" type="{http://www.opentravel.org/OTA/2003/05}RPH_Type" />
 *       &lt;attribute name="InsuranceCompany" use="required" type="{http://www.opentravel.org/OTA/2003/05}StringLength1to64" />
 *       &lt;attribute name="PolicyNmbr" type="{http://www.opentravel.org/OTA/2003/05}StringLength1to64" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OwnInsuranceChoiceType", propOrder = {
        "customerCounts"
})
public class OwnInsuranceChoiceType {

    @XmlElement(name = "CustomerCounts")
    private CustomerCountsType customerCounts;
    @XmlAttribute(name = "RPH")
    private String rph;
    @XmlAttribute(name = "InsuranceCompany", required = true)
    private String insuranceCompany;
    @XmlAttribute(name = "PolicyNmbr")
    private String policyNmbr;

    /**
     * Gets the value of the customerCounts property.
     *
     * @return possible object is
     * {@link CustomerCountsType }
     */
    public CustomerCountsType getCustomerCounts() {
        return customerCounts;
    }

    /**
     * Sets the value of the customerCounts property.
     *
     * @param value allowed object is
     *              {@link CustomerCountsType }
     */
    public void setCustomerCounts(CustomerCountsType value) {
        this.customerCounts = value;
    }

    /**
     * Gets the value of the rph property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getRPH() {
        return rph;
    }

    /**
     * Sets the value of the rph property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setRPH(String value) {
        this.rph = value;
    }

    /**
     * Gets the value of the insuranceCompany property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getInsuranceCompany() {
        return insuranceCompany;
    }

    /**
     * Sets the value of the insuranceCompany property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setInsuranceCompany(String value) {
        this.insuranceCompany = value;
    }

    /**
     * Gets the value of the policyNmbr property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPolicyNmbr() {
        return policyNmbr;
    }

    /**
     * Sets the value of the policyNmbr property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPolicyNmbr(String value) {
        this.policyNmbr = value;
    }

}
