//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.27 at 04:27:20 PM EEST 
//


package com.thomascook.content.bazaarvoice;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the com.thomascook.content.bazaarvoice package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
class ObjectFactory {

    private final static QName _BazaarvoiceOverview_QNAME = new QName("http://www.thomascook.com/content/bazaarvoice", "BazaarvoiceOverview");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.thomascook.content.bazaarvoice
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BazaarvoiceOverviewType }
     */
    public BazaarvoiceOverviewType createBazaarvoiceOverviewType() {
        return new BazaarvoiceOverviewType();
    }

    /**
     * Create an instance of {@link BazaarVoice }
     */
    public BazaarVoice createBazaarVoice() {
        return new BazaarVoice();
    }

    /**
     * Create an instance of {@link BazaarvoiceOverviewType.Properties }
     */
    public BazaarvoiceOverviewType.Properties createBazaarvoiceOverviewTypeProperties() {
        return new BazaarvoiceOverviewType.Properties();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BazaarvoiceOverviewType }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.thomascook.com/content/bazaarvoice", name = "BazaarvoiceOverview")
    public JAXBElement<BazaarvoiceOverviewType> createBazaarvoiceOverview(BazaarvoiceOverviewType value) {
        return new JAXBElement<>(_BazaarvoiceOverview_QNAME, BazaarvoiceOverviewType.class, null, value);
    }

}
