//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.27 at 04:27:20 PM EEST 
//


package org.opentravel.ota._2003._05.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Defines a
 * rectangle-shaped, geographical area with the coordinates of its
 * topleft and bottomright
 * coordinates.
 * <p>
 * <p>
 * <p>Java class for GeoLocationRectangleType complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="GeoLocationRectangleType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TopLeft" type="{http://www.opentravel.org/OTA/2003/05}GeoLocationCoordinateType"/>
 *         &lt;element name="BottomRight" type="{http://www.opentravel.org/OTA/2003/05}GeoLocationCoordinateType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GeoLocationRectangleType", propOrder = {
        "topLeft",
        "bottomRight"
})
public class GeoLocationRectangleType {

    @XmlElement(name = "TopLeft", required = true)
    private GeoLocationCoordinateType topLeft;
    @XmlElement(name = "BottomRight", required = true)
    private GeoLocationCoordinateType bottomRight;

    /**
     * Gets the value of the topLeft property.
     *
     * @return possible object is
     * {@link GeoLocationCoordinateType }
     */
    public GeoLocationCoordinateType getTopLeft() {
        return topLeft;
    }

    /**
     * Sets the value of the topLeft property.
     *
     * @param value allowed object is
     *              {@link GeoLocationCoordinateType }
     */
    public void setTopLeft(GeoLocationCoordinateType value) {
        this.topLeft = value;
    }

    /**
     * Gets the value of the bottomRight property.
     *
     * @return possible object is
     * {@link GeoLocationCoordinateType }
     */
    public GeoLocationCoordinateType getBottomRight() {
        return bottomRight;
    }

    /**
     * Sets the value of the bottomRight property.
     *
     * @param value allowed object is
     *              {@link GeoLocationCoordinateType }
     */
    public void setBottomRight(GeoLocationCoordinateType value) {
        this.bottomRight = value;
    }

}
