//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.27 at 04:27:20 PM EEST 
//


package org.opentravel.ota._2003._05.request;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;
import java.math.BigDecimal;
import java.math.BigInteger;


/**
 * <p>Java class for anonymous complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="POS" type="{http://www.opentravel.org/OTA/2003/05}POS_Type" minOccurs="0"/>
 *         &lt;element name="Service" type="{http://www.opentravel.org/OTA/2003/05}ServiceType" minOccurs="0"/>
 *         &lt;element name="FilterResults" type="{http://www.opentravel.org/OTA/2003/05}FilterResults_Type" minOccurs="0"/>
 *         &lt;element name="SortResults" type="{http://www.opentravel.org/OTA/2003/05}SortResults_Type" minOccurs="0"/>
 *         &lt;element name="ReturnContent" type="{http://www.opentravel.org/OTA/2003/05}ReturnContent_Type" minOccurs="0"/>
 *         &lt;element name="Criteria" type="{http://www.opentravel.org/OTA/2003/05}PkgSearchCriteriaType"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.opentravel.org/OTA/2003/05}OTA_PayloadStdAttributes"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "pos",
        "service",
        "filterResults",
        "sortResults",
        "returnContent",
        "criteria"
})
@XmlRootElement(name = "OTA_PkgSearchRQ")
public class OTAPkgSearchRQ {

    @XmlElement(name = "POS")
    private POSType pos;
    @XmlElement(name = "Service")
    @XmlSchemaType(name = "string")
    private ServiceType service;
    @XmlElement(name = "FilterResults")
    private FilterResultsType filterResults;
    @XmlElement(name = "SortResults")
    private SortResultsType sortResults;
    @XmlElement(name = "ReturnContent")
    private ReturnContentType returnContent;
    @XmlElement(name = "Criteria", required = true)
    private PkgSearchCriteriaType criteria;
    @XmlAttribute(name = "EchoToken")
    private String echoToken;
    @XmlAttribute(name = "TimeStamp")
    @XmlSchemaType(name = "dateTime")
    private XMLGregorianCalendar timeStamp;
    @XmlAttribute(name = "Target")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    private String target;
    @XmlAttribute(name = "Version", required = true)
    private BigDecimal version;
    @XmlAttribute(name = "TransactionIdentifier")
    private String transactionIdentifier;
    @XmlAttribute(name = "SequenceNmbr")
    @XmlSchemaType(name = "nonNegativeInteger")
    private BigInteger sequenceNmbr;
    @XmlAttribute(name = "TransactionStatusCode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    private String transactionStatusCode;
    @XmlAttribute(name = "RetransmissionIndicator")
    private Boolean retransmissionIndicator;
    @XmlAttribute(name = "CorrelationID")
    private String correlationID;
    @XmlAttribute(name = "PrimaryLangID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "language")
    private String primaryLangID;
    @XmlAttribute(name = "AltLangID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "language")
    private String altLangID;

    /**
     * Gets the value of the pos property.
     *
     * @return possible object is
     * {@link POSType }
     */
    public POSType getPOS() {
        return pos;
    }

    /**
     * Sets the value of the pos property.
     *
     * @param value allowed object is
     *              {@link POSType }
     */
    public void setPOS(POSType value) {
        this.pos = value;
    }

    /**
     * Gets the value of the service property.
     *
     * @return possible object is
     * {@link ServiceType }
     */
    public ServiceType getService() {
        return service;
    }

    /**
     * Sets the value of the service property.
     *
     * @param value allowed object is
     *              {@link ServiceType }
     */
    public void setService(ServiceType value) {
        this.service = value;
    }

    /**
     * Gets the value of the filterResults property.
     *
     * @return possible object is
     * {@link FilterResultsType }
     */
    public FilterResultsType getFilterResults() {
        return filterResults;
    }

    /**
     * Sets the value of the filterResults property.
     *
     * @param value allowed object is
     *              {@link FilterResultsType }
     */
    public void setFilterResults(FilterResultsType value) {
        this.filterResults = value;
    }

    /**
     * Gets the value of the sortResults property.
     *
     * @return possible object is
     * {@link SortResultsType }
     */
    public SortResultsType getSortResults() {
        return sortResults;
    }

    /**
     * Sets the value of the sortResults property.
     *
     * @param value allowed object is
     *              {@link SortResultsType }
     */
    public void setSortResults(SortResultsType value) {
        this.sortResults = value;
    }

    /**
     * Gets the value of the returnContent property.
     *
     * @return possible object is
     * {@link ReturnContentType }
     */
    public ReturnContentType getReturnContent() {
        return returnContent;
    }

    /**
     * Sets the value of the returnContent property.
     *
     * @param value allowed object is
     *              {@link ReturnContentType }
     */
    public void setReturnContent(ReturnContentType value) {
        this.returnContent = value;
    }

    /**
     * Gets the value of the criteria property.
     *
     * @return possible object is
     * {@link PkgSearchCriteriaType }
     */
    public PkgSearchCriteriaType getCriteria() {
        return criteria;
    }

    /**
     * Sets the value of the criteria property.
     *
     * @param value allowed object is
     *              {@link PkgSearchCriteriaType }
     */
    public void setCriteria(PkgSearchCriteriaType value) {
        this.criteria = value;
    }

    /**
     * Gets the value of the echoToken property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getEchoToken() {
        return echoToken;
    }

    /**
     * Sets the value of the echoToken property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setEchoToken(String value) {
        this.echoToken = value;
    }

    /**
     * Gets the value of the timeStamp property.
     *
     * @return possible object is
     * {@link XMLGregorianCalendar }
     */
    public XMLGregorianCalendar getTimeStamp() {
        return timeStamp;
    }

    /**
     * Sets the value of the timeStamp property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     */
    public void setTimeStamp(XMLGregorianCalendar value) {
        this.timeStamp = value;
    }

    /**
     * Gets the value of the target property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getTarget() {
        return target;
    }

    /**
     * Sets the value of the target property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setTarget(String value) {
        this.target = value;
    }

    /**
     * Gets the value of the version property.
     *
     * @return possible object is
     * {@link BigDecimal }
     */
    public BigDecimal getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     *
     * @param value allowed object is
     *              {@link BigDecimal }
     */
    public void setVersion(BigDecimal value) {
        this.version = value;
    }

    /**
     * Gets the value of the transactionIdentifier property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getTransactionIdentifier() {
        return transactionIdentifier;
    }

    /**
     * Sets the value of the transactionIdentifier property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setTransactionIdentifier(String value) {
        this.transactionIdentifier = value;
    }

    /**
     * Gets the value of the sequenceNmbr property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    public BigInteger getSequenceNmbr() {
        return sequenceNmbr;
    }

    /**
     * Sets the value of the sequenceNmbr property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setSequenceNmbr(BigInteger value) {
        this.sequenceNmbr = value;
    }

    /**
     * Gets the value of the transactionStatusCode property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getTransactionStatusCode() {
        return transactionStatusCode;
    }

    /**
     * Sets the value of the transactionStatusCode property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setTransactionStatusCode(String value) {
        this.transactionStatusCode = value;
    }

    /**
     * Gets the value of the retransmissionIndicator property.
     *
     * @return possible object is
     * {@link Boolean }
     */
    public Boolean isRetransmissionIndicator() {
        return retransmissionIndicator;
    }

    /**
     * Sets the value of the retransmissionIndicator property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setRetransmissionIndicator(Boolean value) {
        this.retransmissionIndicator = value;
    }

    /**
     * Gets the value of the correlationID property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCorrelationID() {
        return correlationID;
    }

    /**
     * Sets the value of the correlationID property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCorrelationID(String value) {
        this.correlationID = value;
    }

    /**
     * Gets the value of the primaryLangID property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPrimaryLangID() {
        return primaryLangID;
    }

    /**
     * Sets the value of the primaryLangID property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPrimaryLangID(String value) {
        this.primaryLangID = value;
    }

    /**
     * Gets the value of the altLangID property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getAltLangID() {
        return altLangID;
    }

    /**
     * Sets the value of the altLangID property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAltLangID(String value) {
        this.altLangID = value;
    }

}
