//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.27 at 04:27:20 PM EEST 
//


package org.opentravel.ota._2003._05.request;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Used to specify which
 *                 elements are expected in the response for this request.
 *             
 * 
 * <p>Java class for ReturnContent_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ReturnContent_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FacetFieldList" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="FacetField" maxOccurs="9" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.opentravel.org/OTA/2003/05}FieldName">
 *                         &lt;enumeration value="DepAirport"/>
 *                         &lt;enumeration value="ArrAirport"/>
 *                         &lt;enumeration value="DateMonth"/>
 *                         &lt;enumeration value="Brand"/>
 *                         &lt;enumeration value="BoardType"/>
 *                         &lt;enumeration value="Stars"/>
 *                         &lt;enumeration value="ScoreZoover"/>
 *                         &lt;enumeration value="Duration"/>
 *                         &lt;enumeration value="DurationInDays"/>
 *                         &lt;enumeration value="AccommodationType"/>
 *                         &lt;enumeration value="HolidayPeriod"/>
 *                         &lt;enumeration value="Facilities"/>
 *                         &lt;enumeration value="Facilities2"/>
 *                         &lt;enumeration value="Lifestyle"/>
 *                         &lt;enumeration value="Location"/>
 *                         &lt;enumeration value="Activities"/>
 *                         &lt;enumeration value="MarketingLogos1"/>
 *                         &lt;enumeration value="MarketingLogos2"/>
 *                         &lt;enumeration value="MarketingLogos3"/>
 *                         &lt;enumeration value="TripAdvisor"/>
 *                         &lt;enumeration value="ResortCategory"/>
 *                         &lt;enumeration value="RegionCategory"/>
 *                         &lt;enumeration value="DestinationCategory"/>
 *                         &lt;enumeration value="SkiRegion"/>
 *                         &lt;enumeration value="BrochureName"/>
 *                         &lt;enumeration value="CommercialDestination"/>
 *                         &lt;enumeration value="PriceBucket"/>
 *                         &lt;enumeration value="DiscountBucket"/>
 *                         &lt;enumeration value="AbsoluteDiscountBucket"/>
 *                         &lt;enumeration value="FlightTimeBucket"/>
 *                         &lt;enumeration value="Concept"/>
 *                         &lt;enumeration value="FreeChildFlag"/>
 *                         &lt;enumeration value="Stunt"/>
 *                         &lt;enumeration value="HotelChain"/>
 *                         &lt;enumeration value="OfficialRating"/>
 *                         &lt;enumeration value="HotelName"/>
 *                         &lt;enumeration value="HotelCode"/>
 *                         &lt;enumeration value="AverageFlightTime"/>
 *                         &lt;enumeration value="BusTransferTime"/>
 *                         &lt;enumeration value="IncomingDepartureTime"/>
 *                         &lt;enumeration value="OutgoingDepartureTime"/>
 *                         &lt;enumeration value="DepartureDateOnly"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="AvailabilityFieldList" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="AvailabilityField" maxOccurs="2" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.opentravel.org/OTA/2003/05}FieldName">
 *                         &lt;enumeration value="ResortCategory"/>
 *                         &lt;enumeration value="DestinationCategory"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="AvailableDate" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="unit" use="required" type="{http://www.opentravel.org/OTA/2003/05}AvailableDateUnit" />
 *                 &lt;attribute name="inMonth" type="{http://www.w3.org/2001/XMLSchema}gYearMonth" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="returnHotelList" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="returnRankScores" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReturnContent_Type", propOrder = {
    "facetFieldList",
    "availabilityFieldList",
    "availableDate"
})
public class ReturnContentType {

    @XmlElement(name = "FacetFieldList")
    protected FacetFieldList facetFieldList;
    @XmlElement(name = "AvailabilityFieldList")
    protected AvailabilityFieldList availabilityFieldList;
    @XmlElement(name = "AvailableDate")
    protected AvailableDate availableDate;
    @XmlAttribute(name = "returnHotelList")
    protected Boolean returnHotelList;
    @XmlAttribute(name = "returnRankScores")
    protected Boolean returnRankScores;

    /**
     * Gets the value of the facetFieldList property.
     * 
     * @return
     *     possible object is
     *     {@link FacetFieldList }
     *     
     */
    public FacetFieldList getFacetFieldList() {
        return facetFieldList;
    }

    /**
     * Sets the value of the facetFieldList property.
     * 
     * @param value
     *     allowed object is
     *     {@link FacetFieldList }
     *     
     */
    public void setFacetFieldList(FacetFieldList value) {
        this.facetFieldList = value;
    }

    /**
     * Gets the value of the availabilityFieldList property.
     * 
     * @return
     *     possible object is
     *     {@link AvailabilityFieldList }
     *     
     */
    public AvailabilityFieldList getAvailabilityFieldList() {
        return availabilityFieldList;
    }

    /**
     * Sets the value of the availabilityFieldList property.
     * 
     * @param value
     *     allowed object is
     *     {@link AvailabilityFieldList }
     *     
     */
    public void setAvailabilityFieldList(AvailabilityFieldList value) {
        this.availabilityFieldList = value;
    }

    /**
     * Gets the value of the availableDate property.
     * 
     * @return
     *     possible object is
     *     {@link AvailableDate }
     *     
     */
    public AvailableDate getAvailableDate() {
        return availableDate;
    }

    /**
     * Sets the value of the availableDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link AvailableDate }
     *     
     */
    public void setAvailableDate(AvailableDate value) {
        this.availableDate = value;
    }

    /**
     * Gets the value of the returnHotelList property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isReturnHotelList() {
        return returnHotelList;
    }

    /**
     * Sets the value of the returnHotelList property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setReturnHotelList(Boolean value) {
        this.returnHotelList = value;
    }

    /**
     * Gets the value of the returnRankScores property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isReturnRankScores() {
        return returnRankScores;
    }

    /**
     * Sets the value of the returnRankScores property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setReturnRankScores(Boolean value) {
        this.returnRankScores = value;
    }


    /**
     * The list of fields for
     *                             which availability calculation is required. If this element is
     *                             left out, availability
     *                             will be calculated for all possible fields.
     *                             If is is an empty list then no availability calculation will be
     *                             executed for any of the fields.
     *                         
     * 
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="AvailabilityField" maxOccurs="2" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.opentravel.org/OTA/2003/05}FieldName">
     *               &lt;enumeration value="ResortCategory"/>
     *               &lt;enumeration value="DestinationCategory"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "availabilityField"
    })
    public static class AvailabilityFieldList {

        @XmlElement(name = "AvailabilityField")
        protected List<FieldName> availabilityField;

        /**
         * Gets the value of the availabilityField property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the availabilityField property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAvailabilityField().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FieldName }
         * 
         * 
         */
        public List<FieldName> getAvailabilityField() {
            if (availabilityField == null) {
                availabilityField = new ArrayList<FieldName>();
            }
            return this.availabilityField;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="unit" use="required" type="{http://www.opentravel.org/OTA/2003/05}AvailableDateUnit" />
     *       &lt;attribute name="inMonth" type="{http://www.w3.org/2001/XMLSchema}gYearMonth" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class AvailableDate {

        @XmlAttribute(name = "unit", required = true)
        protected AvailableDateUnit unit;
        @XmlAttribute(name = "inMonth")
        @XmlSchemaType(name = "gYearMonth")
        protected XMLGregorianCalendar inMonth;

        /**
         * Gets the value of the unit property.
         * 
         * @return
         *     possible object is
         *     {@link AvailableDateUnit }
         *     
         */
        public AvailableDateUnit getUnit() {
            return unit;
        }

        /**
         * Sets the value of the unit property.
         * 
         * @param value
         *     allowed object is
         *     {@link AvailableDateUnit }
         *     
         */
        public void setUnit(AvailableDateUnit value) {
            this.unit = value;
        }

        /**
         * Gets the value of the inMonth property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getInMonth() {
            return inMonth;
        }

        /**
         * Sets the value of the inMonth property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setInMonth(XMLGregorianCalendar value) {
            this.inMonth = value;
        }

    }


    /**
     * The list of fields for
     *                             which facet calculation is required. If this element is missing,
     *                             facets will be
     *                             calculated for all fields. If it is an empty list
     *                             then no facets will be calculated for any of the fields.
     *                         
     * 
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="FacetField" maxOccurs="9" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.opentravel.org/OTA/2003/05}FieldName">
     *               &lt;enumeration value="DepAirport"/>
     *               &lt;enumeration value="ArrAirport"/>
     *               &lt;enumeration value="DateMonth"/>
     *               &lt;enumeration value="Brand"/>
     *               &lt;enumeration value="BoardType"/>
     *               &lt;enumeration value="Stars"/>
     *               &lt;enumeration value="ScoreZoover"/>
     *               &lt;enumeration value="Duration"/>
     *               &lt;enumeration value="DurationInDays"/>
     *               &lt;enumeration value="AccommodationType"/>
     *               &lt;enumeration value="HolidayPeriod"/>
     *               &lt;enumeration value="Facilities"/>
     *               &lt;enumeration value="Facilities2"/>
     *               &lt;enumeration value="Lifestyle"/>
     *               &lt;enumeration value="Location"/>
     *               &lt;enumeration value="Activities"/>
     *               &lt;enumeration value="MarketingLogos1"/>
     *               &lt;enumeration value="MarketingLogos2"/>
     *               &lt;enumeration value="MarketingLogos3"/>
     *               &lt;enumeration value="TripAdvisor"/>
     *               &lt;enumeration value="ResortCategory"/>
     *               &lt;enumeration value="RegionCategory"/>
     *               &lt;enumeration value="DestinationCategory"/>
     *               &lt;enumeration value="SkiRegion"/>
     *               &lt;enumeration value="BrochureName"/>
     *               &lt;enumeration value="CommercialDestination"/>
     *               &lt;enumeration value="PriceBucket"/>
     *               &lt;enumeration value="DiscountBucket"/>
     *               &lt;enumeration value="AbsoluteDiscountBucket"/>
     *               &lt;enumeration value="FlightTimeBucket"/>
     *               &lt;enumeration value="Concept"/>
     *               &lt;enumeration value="FreeChildFlag"/>
     *               &lt;enumeration value="Stunt"/>
     *               &lt;enumeration value="HotelChain"/>
     *               &lt;enumeration value="OfficialRating"/>
     *               &lt;enumeration value="HotelName"/>
     *               &lt;enumeration value="HotelCode"/>
     *               &lt;enumeration value="AverageFlightTime"/>
     *               &lt;enumeration value="BusTransferTime"/>
     *               &lt;enumeration value="IncomingDepartureTime"/>
     *               &lt;enumeration value="OutgoingDepartureTime"/>
     *               &lt;enumeration value="DepartureDateOnly"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "facetField"
    })
    public static class FacetFieldList {

        @XmlElement(name = "FacetField")
        protected List<FieldName> facetField;

        /**
         * Gets the value of the facetField property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the facetField property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFacetField().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FieldName }
         * 
         * 
         */
        public List<FieldName> getFacetField() {
            if (facetField == null) {
                facetField = new ArrayList<FieldName>();
            }
            return this.facetField;
        }

    }

}
