//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.29 at 06:35:24 PM EEST 
//


package org.opentravel.ota._2003._05.response;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Defines group of free
 *                 child flags. Free child defines how the price of the child is
 *                 calculated for the package.
 *             
 * 
 * <p>Java class for FreeChildFlagsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FreeChildFlagsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FreeChildFlag" type="{http://www.opentravel.org/OTA/2003/05}FreeChildFlagType" maxOccurs="3"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FreeChildFlagsType", propOrder = {
    "freeChildFlag"
})
public class FreeChildFlagsType {

    @XmlElement(name = "FreeChildFlag", required = true)
    @XmlSchemaType(name = "string")
    protected List<FreeChildFlagType> freeChildFlag;

    /**
     * Gets the value of the freeChildFlag property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the freeChildFlag property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFreeChildFlag().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FreeChildFlagType }
     * 
     * 
     */
    public List<FreeChildFlagType> getFreeChildFlag() {
        if (freeChildFlag == null) {
            freeChildFlag = new ArrayList<FreeChildFlagType>();
        }
        return this.freeChildFlag;
    }

}
