//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.29 at 06:35:24 PM EEST 
//


package org.opentravel.ota._2003._05.response;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the org.opentravel.ota._2003._05 package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.opentravel.ota._2003._05
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link OTAPkgSearchRS }
     */
    public OTAPkgSearchRS createOTAPkgSearchRS() {
        return new OTAPkgSearchRS();
    }

    /**
     * Create an instance of {@link RoomStayCandidatesType }
     */
    public RoomStayCandidatesType createRoomStayCandidatesType() {
        return new RoomStayCandidatesType();
    }

    /**
     * Create an instance of {@link PkgGuestCountType }
     */
    public PkgGuestCountType createPkgGuestCountType() {
        return new PkgGuestCountType();
    }

    /**
     * Create an instance of {@link AwardsType }
     */
    public AwardsType createAwardsType() {
        return new AwardsType();
    }

    /**
     * Create an instance of {@link ReturnContentType }
     */
    public ReturnContentType createReturnContentType() {
        return new ReturnContentType();
    }

    /**
     * Create an instance of {@link HotelOfferType }
     */
    public HotelOfferType createHotelOfferType() {
        return new HotelOfferType();
    }

    /**
     * Create an instance of {@link ScoreValuesType }
     */
    public ScoreValuesType createScoreValuesType() {
        return new ScoreValuesType();
    }

    /**
     * Create an instance of {@link SortResultsType }
     */
    public SortResultsType createSortResultsType() {
        return new SortResultsType();
    }

    /**
     * Create an instance of {@link SourceType }
     */
    public SourceType createSourceType() {
        return new SourceType();
    }

    /**
     * Create an instance of {@link PkgSearchCriteriaType }
     */
    public PkgSearchCriteriaType createPkgSearchCriteriaType() {
        return new PkgSearchCriteriaType();
    }

    /**
     * Create an instance of {@link PkgSearchCriteriaType.PkgCriterion }
     */
    public PkgSearchCriteriaType.PkgCriterion createPkgSearchCriteriaTypePkgCriterion() {
        return new PkgSearchCriteriaType.PkgCriterion();
    }

    /**
     * Create an instance of {@link PkgSearchCriteriaType.PkgCriterion.AdditionalCriteria }
     */
    public PkgSearchCriteriaType.PkgCriterion.AdditionalCriteria createPkgSearchCriteriaTypePkgCriterionAdditionalCriteria() {
        return new PkgSearchCriteriaType.PkgCriterion.AdditionalCriteria();
    }

    /**
     * Create an instance of {@link PkgSearchCriteriaType.PkgCriterion.AdditionalCriteria.Criterion }
     */
    public PkgSearchCriteriaType.PkgCriterion.AdditionalCriteria.Criterion createPkgSearchCriteriaTypePkgCriterionAdditionalCriteriaCriterion() {
        return new PkgSearchCriteriaType.PkgCriterion.AdditionalCriteria.Criterion();
    }

    /**
     * Create an instance of {@link PkgValueMatchType }
     */
    public PkgValueMatchType createPkgValueMatchType() {
        return new PkgValueMatchType();
    }

    /**
     * Create an instance of {@link PkgValueMatchType.PriceInfo }
     */
    public PkgValueMatchType.PriceInfo createPkgValueMatchTypePriceInfo() {
        return new PkgValueMatchType.PriceInfo();
    }

    /**
     * Create an instance of {@link AvailabilitySearchResponseType }
     */
    public AvailabilitySearchResponseType createAvailabilitySearchResponseType() {
        return new AvailabilitySearchResponseType();
    }

    /**
     * Create an instance of {@link AvailabilitySearchResponseType.Availability }
     */
    public AvailabilitySearchResponseType.Availability createAvailabilitySearchResponseTypeAvailability() {
        return new AvailabilitySearchResponseType.Availability();
    }

    /**
     * Create an instance of {@link FacetSearchResponseType }
     */
    public FacetSearchResponseType createFacetSearchResponseType() {
        return new FacetSearchResponseType();
    }

    /**
     * Create an instance of {@link FacetSearchResponseType.Facet }
     */
    public FacetSearchResponseType.Facet createFacetSearchResponseTypeFacet() {
        return new FacetSearchResponseType.Facet();
    }

    /**
     * Create an instance of {@link POSType }
     */
    public POSType createPOSType() {
        return new POSType();
    }

    /**
     * Create an instance of {@link VersionInfoType }
     */
    public VersionInfoType createVersionInfoType() {
        return new VersionInfoType();
    }

    /**
     * Create an instance of {@link TraceDetailType }
     */
    public TraceDetailType createTraceDetailType() {
        return new TraceDetailType();
    }

    /**
     * Create an instance of {@link SuccessType }
     */
    public SuccessType createSuccessType() {
        return new SuccessType();
    }

    /**
     * Create an instance of {@link WarningsType }
     */
    public WarningsType createWarningsType() {
        return new WarningsType();
    }

    /**
     * Create an instance of {@link OTAPkgSearchRS.HotelOffers }
     */
    public OTAPkgSearchRS.HotelOffers createOTAPkgSearchRSHotelOffers() {
        return new OTAPkgSearchRS.HotelOffers();
    }

    /**
     * Create an instance of {@link OTAPkgSearchRS.Segment }
     */
    public OTAPkgSearchRS.Segment createOTAPkgSearchRSSegment() {
        return new OTAPkgSearchRS.Segment();
    }

    /**
     * Create an instance of {@link ErrorsType }
     */
    public ErrorsType createErrorsType() {
        return new ErrorsType();
    }

    /**
     * Create an instance of {@link OriginCodesType }
     */
    public OriginCodesType createOriginCodesType() {
        return new OriginCodesType();
    }

    /**
     * Create an instance of {@link FilterResultsType }
     */
    public FilterResultsType createFilterResultsType() {
        return new FilterResultsType();
    }

    /**
     * Create an instance of {@link BrandsType }
     */
    public BrandsType createBrandsType() {
        return new BrandsType();
    }

    /**
     * Create an instance of {@link ConceptType }
     */
    public ConceptType createConceptType() {
        return new ConceptType();
    }

    /**
     * Create an instance of {@link ArrivalAirportListType }
     */
    public ArrivalAirportListType createArrivalAirportListType() {
        return new ArrivalAirportListType();
    }

    /**
     * Create an instance of {@link DurationsType }
     */
    public DurationsType createDurationsType() {
        return new DurationsType();
    }

    /**
     * Create an instance of {@link DurationInDaysType }
     */
    public DurationInDaysType createDurationInDaysType() {
        return new DurationInDaysType();
    }

    /**
     * Create an instance of {@link StuntsType }
     */
    public StuntsType createStuntsType() {
        return new StuntsType();
    }

    /**
     * Create an instance of {@link ConceptsType }
     */
    public ConceptsType createConceptsType() {
        return new ConceptsType();
    }

    /**
     * Create an instance of {@link DepartureAirportListType }
     */
    public DepartureAirportListType createDepartureAirportListType() {
        return new DepartureAirportListType();
    }

    /**
     * Create an instance of {@link PkgFlightType }
     */
    public PkgFlightType createPkgFlightType() {
        return new PkgFlightType();
    }

    /**
     * Create an instance of {@link PkgRoomStayCandidateType }
     */
    public PkgRoomStayCandidateType createPkgRoomStayCandidateType() {
        return new PkgRoomStayCandidateType();
    }

    /**
     * Create an instance of {@link UniqueIDType }
     */
    public UniqueIDType createUniqueIDType() {
        return new UniqueIDType();
    }

    /**
     * Create an instance of {@link ErrorType }
     */
    public ErrorType createErrorType() {
        return new ErrorType();
    }

    /**
     * Create an instance of {@link CompanyNameType }
     */
    public CompanyNameType createCompanyNameType() {
        return new CompanyNameType();
    }

    /**
     * Create an instance of {@link FreeTextType }
     */
    public FreeTextType createFreeTextType() {
        return new FreeTextType();
    }

    /**
     * Create an instance of {@link GeoLocationCoordinateType }
     */
    public GeoLocationCoordinateType createGeoLocationCoordinateType() {
        return new GeoLocationCoordinateType();
    }

    /**
     * Create an instance of {@link WarningType }
     */
    public WarningType createWarningType() {
        return new WarningType();
    }

    /**
     * Create an instance of {@link InAndOutBoundFlightsType }
     */
    public InAndOutBoundFlightsType createInAndOutBoundFlightsType() {
        return new InAndOutBoundFlightsType();
    }

    /**
     * Create an instance of {@link GeoLocationRectangleType }
     */
    public GeoLocationRectangleType createGeoLocationRectangleType() {
        return new GeoLocationRectangleType();
    }

    /**
     * Create an instance of {@link FreeChildFlagsType }
     */
    public FreeChildFlagsType createFreeChildFlagsType() {
        return new FreeChildFlagsType();
    }

    /**
     * Create an instance of {@link BookingIDType }
     */
    public BookingIDType createBookingIDType() {
        return new BookingIDType();
    }

    /**
     * Create an instance of {@link DurationDaysType }
     */
    public DurationDaysType createDurationDaysType() {
        return new DurationDaysType();
    }

    /**
     * Create an instance of {@link PkgPriceBreakdownType }
     */
    public PkgPriceBreakdownType createPkgPriceBreakdownType() {
        return new PkgPriceBreakdownType();
    }

    /**
     * Create an instance of {@link LocationType }
     */
    public LocationType createLocationType() {
        return new LocationType();
    }

    /**
     * Create an instance of {@link BoardCodesType }
     */
    public BoardCodesType createBoardCodesType() {
        return new BoardCodesType();
    }

    /**
     * Create an instance of {@link SolrFieldType }
     */
    public SolrFieldType createSolrFieldType() {
        return new SolrFieldType();
    }

    /**
     * Create an instance of {@link RoomStayCandidatesType.RoomStayCandidate }
     */
    public RoomStayCandidatesType.RoomStayCandidate createRoomStayCandidatesTypeRoomStayCandidate() {
        return new RoomStayCandidatesType.RoomStayCandidate();
    }

    /**
     * Create an instance of {@link PkgGuestCountType.GuestCount }
     */
    public PkgGuestCountType.GuestCount createPkgGuestCountTypeGuestCount() {
        return new PkgGuestCountType.GuestCount();
    }

    /**
     * Create an instance of {@link AwardsType.Award }
     */
    public AwardsType.Award createAwardsTypeAward() {
        return new AwardsType.Award();
    }

    /**
     * Create an instance of {@link ReturnContentType.FacetFieldList }
     */
    public ReturnContentType.FacetFieldList createReturnContentTypeFacetFieldList() {
        return new ReturnContentType.FacetFieldList();
    }

    /**
     * Create an instance of {@link ReturnContentType.AvailabilityFieldList }
     */
    public ReturnContentType.AvailabilityFieldList createReturnContentTypeAvailabilityFieldList() {
        return new ReturnContentType.AvailabilityFieldList();
    }

    /**
     * Create an instance of {@link ReturnContentType.AvailableDate }
     */
    public ReturnContentType.AvailableDate createReturnContentTypeAvailableDate() {
        return new ReturnContentType.AvailableDate();
    }

    /**
     * Create an instance of {@link HotelOfferType.Rooms }
     */
    public HotelOfferType.Rooms createHotelOfferTypeRooms() {
        return new HotelOfferType.Rooms();
    }

    /**
     * Create an instance of {@link ScoreValuesType.ScoreValue }
     */
    public ScoreValuesType.ScoreValue createScoreValuesTypeScoreValue() {
        return new ScoreValuesType.ScoreValue();
    }

    /**
     * Create an instance of {@link SortResultsType.SortResult }
     */
    public SortResultsType.SortResult createSortResultsTypeSortResult() {
        return new SortResultsType.SortResult();
    }

    /**
     * Create an instance of {@link SourceType.RequestorID }
     */
    public SourceType.RequestorID createSourceTypeRequestorID() {
        return new SourceType.RequestorID();
    }

    /**
     * Create an instance of {@link SourceType.Position }
     */
    public SourceType.Position createSourceTypePosition() {
        return new SourceType.Position();
    }

    /**
     * Create an instance of {@link SourceType.BookingChannel }
     */
    public SourceType.BookingChannel createSourceTypeBookingChannel() {
        return new SourceType.BookingChannel();
    }

    /**
     * Create an instance of {@link PkgSearchCriteriaType.PkgCriterion.AdultGroupAge }
     */
    public PkgSearchCriteriaType.PkgCriterion.AdultGroupAge createPkgSearchCriteriaTypePkgCriterionAdultGroupAge() {
        return new PkgSearchCriteriaType.PkgCriterion.AdultGroupAge();
    }

    /**
     * Create an instance of {@link PkgSearchCriteriaType.PkgCriterion.StayDateRange }
     */
    public PkgSearchCriteriaType.PkgCriterion.StayDateRange createPkgSearchCriteriaTypePkgCriterionStayDateRange() {
        return new PkgSearchCriteriaType.PkgCriterion.StayDateRange();
    }

    /**
     * Create an instance of {@link PkgSearchCriteriaType.PkgCriterion.CommercialDestinations }
     */
    public PkgSearchCriteriaType.PkgCriterion.CommercialDestinations createPkgSearchCriteriaTypePkgCriterionCommercialDestinations() {
        return new PkgSearchCriteriaType.PkgCriterion.CommercialDestinations();
    }

    /**
     * Create an instance of {@link PkgSearchCriteriaType.PkgCriterion.DestinationCategories }
     */
    public PkgSearchCriteriaType.PkgCriterion.DestinationCategories createPkgSearchCriteriaTypePkgCriterionDestinationCategories() {
        return new PkgSearchCriteriaType.PkgCriterion.DestinationCategories();
    }

    /**
     * Create an instance of {@link PkgSearchCriteriaType.PkgCriterion.ResortCategories }
     */
    public PkgSearchCriteriaType.PkgCriterion.ResortCategories createPkgSearchCriteriaTypePkgCriterionResortCategories() {
        return new PkgSearchCriteriaType.PkgCriterion.ResortCategories();
    }

    /**
     * Create an instance of {@link PkgSearchCriteriaType.PkgCriterion.TimeInterval }
     */
    public PkgSearchCriteriaType.PkgCriterion.TimeInterval createPkgSearchCriteriaTypePkgCriterionTimeInterval() {
        return new PkgSearchCriteriaType.PkgCriterion.TimeInterval();
    }

    /**
     * Create an instance of {@link PkgSearchCriteriaType.PkgCriterion.AdditionalCriteria.Criterion.Option }
     */
    public PkgSearchCriteriaType.PkgCriterion.AdditionalCriteria.Criterion.Option createPkgSearchCriteriaTypePkgCriterionAdditionalCriteriaCriterionOption() {
        return new PkgSearchCriteriaType.PkgCriterion.AdditionalCriteria.Criterion.Option();
    }

    /**
     * Create an instance of {@link PkgValueMatchType.PriceInfo.PriceBreakdown }
     */
    public PkgValueMatchType.PriceInfo.PriceBreakdown createPkgValueMatchTypePriceInfoPriceBreakdown() {
        return new PkgValueMatchType.PriceInfo.PriceBreakdown();
    }

    /**
     * Create an instance of {@link AvailabilitySearchResponseType.Availability.AvailableValue }
     */
    public AvailabilitySearchResponseType.Availability.AvailableValue createAvailabilitySearchResponseTypeAvailabilityAvailableValue() {
        return new AvailabilitySearchResponseType.Availability.AvailableValue();
    }

    /**
     * Create an instance of {@link FacetSearchResponseType.Facet.FacetCount }
     */
    public FacetSearchResponseType.Facet.FacetCount createFacetSearchResponseTypeFacetFacetCount() {
        return new FacetSearchResponseType.Facet.FacetCount();
    }

}
