//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.06 at 04:28:21 PM EEST 
//


package com.thomascook.wrAdapter.request;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.util.ArrayList;
import java.util.List;


/**
 * Name of an individual and
 * appropriate contact information. May be contact information for the
 * customer or someone affiliated with the customer.
 * <p>
 * <p>
 * <p>Java class for ContactPersonType complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="ContactPersonType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PersonName" type="{}PersonNameType" minOccurs="0"/>
 *         &lt;element name="CustomerReference" type="{}StringLength1to255" minOccurs="0"/>
 *         &lt;element name="Telephone" maxOccurs="5" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attGroup ref="{}TelephoneInfoGroup"/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Address" type="{}AddressInfoType" maxOccurs="5" minOccurs="0"/>
 *         &lt;element name="Email" type="{}StringLength1to255" maxOccurs="5" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="MarketingOptIn" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="EmailOptIn" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="SMSOptIn" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="LettersOptIn" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="PhoneOptIn" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="DOB" type="{http://www.w3.org/2001/XMLSchema}date" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ContactPersonType", propOrder = {
        "personName",
        "customerReference",
        "telephone",
        "address",
        "email"
})
public class ContactPersonType {

    @XmlElement(name = "PersonName")
    protected PersonNameType personName;
    @XmlElement(name = "CustomerReference")
    protected String customerReference;
    @XmlElement(name = "Telephone")
    protected List<Telephone> telephone;
    @XmlElement(name = "Address")
    protected List<AddressInfoType> address;
    @XmlElement(name = "Email")
    protected List<String> email;
    @XmlAttribute(name = "MarketingOptIn")
    protected Boolean marketingOptIn;
    @XmlAttribute(name = "EmailOptIn")
    protected Boolean emailOptIn;
    @XmlAttribute(name = "SMSOptIn")
    protected Boolean smsOptIn;
    @XmlAttribute(name = "LettersOptIn")
    protected Boolean lettersOptIn;
    @XmlAttribute(name = "PhoneOptIn")
    protected Boolean phoneOptIn;
    @XmlAttribute(name = "DOB")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dob;

    /**
     * Gets the value of the personName property.
     *
     * @return possible object is
     * {@link PersonNameType }
     */
    public PersonNameType getPersonName() {
        return personName;
    }

    /**
     * Sets the value of the personName property.
     *
     * @param value allowed object is
     *              {@link PersonNameType }
     */
    public void setPersonName(PersonNameType value) {
        this.personName = value;
    }

    /**
     * Gets the value of the customerReference property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCustomerReference() {
        return customerReference;
    }

    /**
     * Sets the value of the customerReference property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCustomerReference(String value) {
        this.customerReference = value;
    }

    /**
     * Gets the value of the telephone property.
     * <p>
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the telephone property.
     * <p>
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTelephone().add(newItem);
     * </pre>
     * <p>
     * <p>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Telephone }
     */
    public List<Telephone> getTelephone() {
        if (telephone == null) {
            telephone = new ArrayList<Telephone>();
        }
        return this.telephone;
    }

    /**
     * Gets the value of the address property.
     * <p>
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the address property.
     * <p>
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAddress().add(newItem);
     * </pre>
     * <p>
     * <p>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AddressInfoType }
     */
    public List<AddressInfoType> getAddress() {
        if (address == null) {
            address = new ArrayList<AddressInfoType>();
        }
        return this.address;
    }

    /**
     * Gets the value of the email property.
     * <p>
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the email property.
     * <p>
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEmail().add(newItem);
     * </pre>
     * <p>
     * <p>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     */
    public List<String> getEmail() {
        if (email == null) {
            email = new ArrayList<String>();
        }
        return this.email;
    }

    /**
     * Gets the value of the marketingOptIn property.
     *
     * @return possible object is
     * {@link Boolean }
     */
    public boolean isMarketingOptIn() {
        if (marketingOptIn == null) {
            return false;
        } else {
            return marketingOptIn;
        }
    }

    /**
     * Sets the value of the marketingOptIn property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setMarketingOptIn(Boolean value) {
        this.marketingOptIn = value;
    }

    /**
     * Gets the value of the emailOptIn property.
     *
     * @return possible object is
     * {@link Boolean }
     */
    public boolean isEmailOptIn() {
        if (emailOptIn == null) {
            return false;
        } else {
            return emailOptIn;
        }
    }

    /**
     * Sets the value of the emailOptIn property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setEmailOptIn(Boolean value) {
        this.emailOptIn = value;
    }

    /**
     * Gets the value of the smsOptIn property.
     *
     * @return possible object is
     * {@link Boolean }
     */
    public boolean isSMSOptIn() {
        if (smsOptIn == null) {
            return false;
        } else {
            return smsOptIn;
        }
    }

    /**
     * Sets the value of the smsOptIn property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setSMSOptIn(Boolean value) {
        this.smsOptIn = value;
    }

    /**
     * Gets the value of the lettersOptIn property.
     *
     * @return possible object is
     * {@link Boolean }
     */
    public boolean isLettersOptIn() {
        if (lettersOptIn == null) {
            return false;
        } else {
            return lettersOptIn;
        }
    }

    /**
     * Sets the value of the lettersOptIn property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setLettersOptIn(Boolean value) {
        this.lettersOptIn = value;
    }

    /**
     * Gets the value of the phoneOptIn property.
     *
     * @return possible object is
     * {@link Boolean }
     */
    public boolean isPhoneOptIn() {
        if (phoneOptIn == null) {
            return false;
        } else {
            return phoneOptIn;
        }
    }

    /**
     * Sets the value of the phoneOptIn property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setPhoneOptIn(Boolean value) {
        this.phoneOptIn = value;
    }

    /**
     * Gets the value of the dob property.
     *
     * @return possible object is
     * {@link XMLGregorianCalendar }
     */
    public XMLGregorianCalendar getDOB() {
        return dob;
    }

    /**
     * Sets the value of the dob property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     */
    public void setDOB(XMLGregorianCalendar value) {
        this.dob = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * <p>
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attGroup ref="{}TelephoneInfoGroup"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Telephone {

        @XmlAttribute(name = "PhoneTechType")
        protected String phoneTechType;
        @XmlAttribute(name = "PhoneUseType")
        protected String phoneUseType;
        @XmlAttribute(name = "PhoneNumber", required = true)
        protected String phoneNumber;
        @XmlAttribute(name = "AreaCityCode")
        protected String areaCityCode;

        /**
         * Gets the value of the phoneTechType property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getPhoneTechType() {
            return phoneTechType;
        }

        /**
         * Sets the value of the phoneTechType property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setPhoneTechType(String value) {
            this.phoneTechType = value;
        }

        /**
         * Gets the value of the phoneUseType property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getPhoneUseType() {
            return phoneUseType;
        }

        /**
         * Sets the value of the phoneUseType property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setPhoneUseType(String value) {
            this.phoneUseType = value;
        }

        /**
         * Gets the value of the phoneNumber property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getPhoneNumber() {
            return phoneNumber;
        }

        /**
         * Sets the value of the phoneNumber property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setPhoneNumber(String value) {
            this.phoneNumber = value;
        }

        /**
         * Gets the value of the areaCityCode property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getAreaCityCode() {
            return areaCityCode;
        }

        /**
         * Sets the value of the areaCityCode property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setAreaCityCode(String value) {
            this.areaCityCode = value;
        }

    }

}
