//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.30 at 10:58:08 AM EEST 
//


package com.thomascook.nurvisAdapter.request;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * To store or to show all bookable information
 * <p>
 * <p>
 * <p>Java class for Reservation-FabType-Request complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="Reservation-FabType-Request">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TOCode" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Catalog" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Currency" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Price" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="AccountNr">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="-?[0-9]+"/>
 *               &lt;maxLength value="8"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="AddPrice" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Fat" type="{}Reservation-FatType-Request" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Fah" type="{}Reservation-FahType-Request" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Fac" type="{}Reservation-FacType-Request" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Fap" type="{}Reservation-FapType-Request" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Customer" type="{}Reservation-CustomerType-Request" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Key">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="1000"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="SellAgent">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="6"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Reservation-FabType-Request", propOrder = {
        "toCode",
        "catalog",
        "currency",
        "price",
        "accountNr",
        "addPrice",
        "fat",
        "fah",
        "fac",
        "fap",
        "customer"
})
public class ReservationFabTypeRequest {

    @XmlElement(name = "TOCode")
    private String toCode;
    @XmlElement(name = "Catalog")
    private String catalog;
    @XmlElement(name = "Currency")
    private String currency;
    @XmlElement(name = "Price")
    private String price;
    @XmlElement(name = "AccountNr", required = true)
    private String accountNr;
    @XmlElement(name = "AddPrice")
    private String addPrice;
    @XmlElement(name = "Fat")
    private List<ReservationFatTypeRequest> fat;
    @XmlElement(name = "Fah")
    private List<ReservationFahTypeRequest> fah;
    @XmlElement(name = "Fac")
    private List<ReservationFacTypeRequest> fac;
    @XmlElement(name = "Fap")
    private List<ReservationFapTypeRequest> fap;
    @XmlElement(name = "Customer")
    private ReservationCustomerTypeRequest customer;
    @XmlAttribute(name = "Key")
    private String key;
    @XmlAttribute(name = "SellAgent")
    private String sellAgent;

    /**
     * Gets the value of the toCode property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getTOCode() {
        return toCode;
    }

    /**
     * Sets the value of the toCode property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setTOCode(String value) {
        this.toCode = value;
    }

    /**
     * Gets the value of the catalog property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCatalog() {
        return catalog;
    }

    /**
     * Sets the value of the catalog property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCatalog(String value) {
        this.catalog = value;
    }

    /**
     * Gets the value of the currency property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCurrency(String value) {
        this.currency = value;
    }

    /**
     * Gets the value of the price property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPrice() {
        return price;
    }

    /**
     * Sets the value of the price property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPrice(String value) {
        this.price = value;
    }

    /**
     * Gets the value of the accountNr property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getAccountNr() {
        return accountNr;
    }

    /**
     * Sets the value of the accountNr property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAccountNr(String value) {
        this.accountNr = value;
    }

    /**
     * Gets the value of the addPrice property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getAddPrice() {
        return addPrice;
    }

    /**
     * Sets the value of the addPrice property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAddPrice(String value) {
        this.addPrice = value;
    }

    /**
     * Gets the value of the fat property.
     * <p>
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fat property.
     * <p>
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFat().add(newItem);
     * </pre>
     * <p>
     * <p>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReservationFatTypeRequest }
     */
    public List<ReservationFatTypeRequest> getFat() {
        if (fat == null) {
            fat = new ArrayList<>();
        }
        return this.fat;
    }

    /**
     * Gets the value of the fah property.
     * <p>
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fah property.
     * <p>
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFah().add(newItem);
     * </pre>
     * <p>
     * <p>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReservationFahTypeRequest }
     */
    public List<ReservationFahTypeRequest> getFah() {
        if (fah == null) {
            fah = new ArrayList<>();
        }
        return this.fah;
    }

    /**
     * Gets the value of the fac property.
     * <p>
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fac property.
     * <p>
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFac().add(newItem);
     * </pre>
     * <p>
     * <p>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReservationFacTypeRequest }
     */
    public List<ReservationFacTypeRequest> getFac() {
        if (fac == null) {
            fac = new ArrayList<>();
        }
        return this.fac;
    }

    /**
     * Gets the value of the fap property.
     * <p>
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fap property.
     * <p>
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFap().add(newItem);
     * </pre>
     * <p>
     * <p>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReservationFapTypeRequest }
     */
    public List<ReservationFapTypeRequest> getFap() {
        if (fap == null) {
            fap = new ArrayList<>();
        }
        return this.fap;
    }

    /**
     * Gets the value of the customer property.
     *
     * @return possible object is
     * {@link ReservationCustomerTypeRequest }
     */
    public ReservationCustomerTypeRequest getCustomer() {
        return customer;
    }

    /**
     * Sets the value of the customer property.
     *
     * @param value allowed object is
     *              {@link ReservationCustomerTypeRequest }
     */
    public void setCustomer(ReservationCustomerTypeRequest value) {
        this.customer = value;
    }

    /**
     * Gets the value of the key property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getKey() {
        return key;
    }

    /**
     * Sets the value of the key property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setKey(String value) {
        this.key = value;
    }

    /**
     * Gets the value of the sellAgent property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSellAgent() {
        return sellAgent;
    }

    /**
     * Sets the value of the sellAgent property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSellAgent(String value) {
        this.sellAgent = value;
    }

}
