//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.30 at 10:58:08 AM EEST 
//


package com.thomascook.nurvisAdapter.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Customer-data
 * <p>
 * <p>
 * <p>Java class for Reservation-CustomerType-Request complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="Reservation-CustomerType-Request">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="C_Name" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="40"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="C_FirstName" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="C_Title" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="C_PersonType" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="01"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="C_Country" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="03"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="C_Language" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="01"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="C_Street" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="46"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="C_HouseNr" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="08"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="C_POCode" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="C_City" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="40"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="C_AdrExtra" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="30"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="C_TelNr" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="16"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="C_Mobile" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="16"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="C_HomeContactNr" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="16"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="C_ContactChannel" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="C_EMailUser" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="64"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="C_EMailDomain" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="64"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Reservation-CustomerType-Request", propOrder = {
        "cName",
        "cFirstName",
        "cTitle",
        "cPersonType",
        "cCountry",
        "cLanguage",
        "cStreet",
        "cHouseNr",
        "cpoCode",
        "cCity",
        "cAdrExtra",
        "cTelNr",
        "cMobile",
        "cHomeContactNr",
        "cContactChannel",
        "ceMailUser",
        "ceMailDomain"
})
public class ReservationCustomerTypeRequest {

    @XmlElement(name = "C_Name")
    private String cName;
    @XmlElement(name = "C_FirstName")
    private String cFirstName;
    @XmlElement(name = "C_Title")
    private String cTitle;
    @XmlElement(name = "C_PersonType")
    private String cPersonType;
    @XmlElement(name = "C_Country")
    private String cCountry;
    @XmlElement(name = "C_Language")
    private String cLanguage;
    @XmlElement(name = "C_Street")
    private String cStreet;
    @XmlElement(name = "C_HouseNr")
    private String cHouseNr;
    @XmlElement(name = "C_POCode")
    private String cpoCode;
    @XmlElement(name = "C_City")
    private String cCity;
    @XmlElement(name = "C_AdrExtra")
    private String cAdrExtra;
    @XmlElement(name = "C_TelNr")
    private String cTelNr;
    @XmlElement(name = "C_Mobile")
    private String cMobile;
    @XmlElement(name = "C_HomeContactNr")
    private String cHomeContactNr;
    @XmlElement(name = "C_ContactChannel")
    private String cContactChannel;
    @XmlElement(name = "C_EMailUser")
    private String ceMailUser;
    @XmlElement(name = "C_EMailDomain")
    private String ceMailDomain;

    /**
     * Gets the value of the cName property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCName() {
        return cName;
    }

    /**
     * Sets the value of the cName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCName(String value) {
        this.cName = value;
    }

    /**
     * Gets the value of the cFirstName property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCFirstName() {
        return cFirstName;
    }

    /**
     * Sets the value of the cFirstName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCFirstName(String value) {
        this.cFirstName = value;
    }

    /**
     * Gets the value of the cTitle property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCTitle() {
        return cTitle;
    }

    /**
     * Sets the value of the cTitle property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCTitle(String value) {
        this.cTitle = value;
    }

    /**
     * Gets the value of the cPersonType property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCPersonType() {
        return cPersonType;
    }

    /**
     * Sets the value of the cPersonType property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCPersonType(String value) {
        this.cPersonType = value;
    }

    /**
     * Gets the value of the cCountry property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCCountry() {
        return cCountry;
    }

    /**
     * Sets the value of the cCountry property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCCountry(String value) {
        this.cCountry = value;
    }

    /**
     * Gets the value of the cLanguage property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCLanguage() {
        return cLanguage;
    }

    /**
     * Sets the value of the cLanguage property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCLanguage(String value) {
        this.cLanguage = value;
    }

    /**
     * Gets the value of the cStreet property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCStreet() {
        return cStreet;
    }

    /**
     * Sets the value of the cStreet property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCStreet(String value) {
        this.cStreet = value;
    }

    /**
     * Gets the value of the cHouseNr property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCHouseNr() {
        return cHouseNr;
    }

    /**
     * Sets the value of the cHouseNr property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCHouseNr(String value) {
        this.cHouseNr = value;
    }

    /**
     * Gets the value of the cpoCode property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCPOCode() {
        return cpoCode;
    }

    /**
     * Sets the value of the cpoCode property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCPOCode(String value) {
        this.cpoCode = value;
    }

    /**
     * Gets the value of the cCity property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCCity() {
        return cCity;
    }

    /**
     * Sets the value of the cCity property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCCity(String value) {
        this.cCity = value;
    }

    /**
     * Gets the value of the cAdrExtra property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCAdrExtra() {
        return cAdrExtra;
    }

    /**
     * Sets the value of the cAdrExtra property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCAdrExtra(String value) {
        this.cAdrExtra = value;
    }

    /**
     * Gets the value of the cTelNr property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCTelNr() {
        return cTelNr;
    }

    /**
     * Sets the value of the cTelNr property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCTelNr(String value) {
        this.cTelNr = value;
    }

    /**
     * Gets the value of the cMobile property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCMobile() {
        return cMobile;
    }

    /**
     * Sets the value of the cMobile property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCMobile(String value) {
        this.cMobile = value;
    }

    /**
     * Gets the value of the cHomeContactNr property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCHomeContactNr() {
        return cHomeContactNr;
    }

    /**
     * Sets the value of the cHomeContactNr property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCHomeContactNr(String value) {
        this.cHomeContactNr = value;
    }

    /**
     * Gets the value of the cContactChannel property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCContactChannel() {
        return cContactChannel;
    }

    /**
     * Sets the value of the cContactChannel property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCContactChannel(String value) {
        this.cContactChannel = value;
    }

    /**
     * Gets the value of the ceMailUser property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCEMailUser() {
        return ceMailUser;
    }

    /**
     * Sets the value of the ceMailUser property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCEMailUser(String value) {
        this.ceMailUser = value;
    }

    /**
     * Gets the value of the ceMailDomain property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCEMailDomain() {
        return ceMailDomain;
    }

    /**
     * Sets the value of the ceMailDomain property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCEMailDomain(String value) {
        this.ceMailDomain = value;
    }

}
