//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.27 at 04:27:20 PM EEST 
//


package com.thomascook.content.roomcontent;

import com.thomascook.content.common.MediaType;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for RoomType complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="RoomType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RoomDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RoomDetails" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RoomAmenities" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MinAdultOccupancy" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="MaxAdultOccupancy" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="MinChildOccupancy" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="MaxChildOccupancy" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="MediaItems" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="MediaItem" type="{http://www.thomascook.com/content/common}MediaType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="RoomCode" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RoomType", propOrder = {
        "roomDescription",
        "roomDetails",
        "roomAmenities",
        "minAdultOccupancy",
        "maxAdultOccupancy",
        "minChildOccupancy",
        "maxChildOccupancy",
        "mediaItems"
})
public class RoomType {

    @XmlElement(name = "RoomDescription")
    private String roomDescription;
    @XmlElement(name = "RoomDetails")
    private String roomDetails;
    @XmlElement(name = "RoomAmenities")
    private String roomAmenities;
    @XmlElement(name = "MinAdultOccupancy")
    private Integer minAdultOccupancy;
    @XmlElement(name = "MaxAdultOccupancy")
    private Integer maxAdultOccupancy;
    @XmlElement(name = "MinChildOccupancy")
    private Integer minChildOccupancy;
    @XmlElement(name = "MaxChildOccupancy")
    private Integer maxChildOccupancy;
    @XmlElement(name = "MediaItems")
    private MediaItems mediaItems;
    @XmlAttribute(name = "RoomCode", required = true)
    private String roomCode;

    /**
     * Gets the value of the roomDescription property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getRoomDescription() {
        return roomDescription;
    }

    /**
     * Sets the value of the roomDescription property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setRoomDescription(String value) {
        this.roomDescription = value;
    }

    /**
     * Gets the value of the roomDetails property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getRoomDetails() {
        return roomDetails;
    }

    /**
     * Sets the value of the roomDetails property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setRoomDetails(String value) {
        this.roomDetails = value;
    }

    /**
     * Gets the value of the roomAmenities property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getRoomAmenities() {
        return roomAmenities;
    }

    /**
     * Sets the value of the roomAmenities property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setRoomAmenities(String value) {
        this.roomAmenities = value;
    }

    /**
     * Gets the value of the minAdultOccupancy property.
     *
     * @return possible object is
     * {@link Integer }
     */
    public Integer getMinAdultOccupancy() {
        return minAdultOccupancy;
    }

    /**
     * Sets the value of the minAdultOccupancy property.
     *
     * @param value allowed object is
     *              {@link Integer }
     */
    public void setMinAdultOccupancy(Integer value) {
        this.minAdultOccupancy = value;
    }

    /**
     * Gets the value of the maxAdultOccupancy property.
     *
     * @return possible object is
     * {@link Integer }
     */
    public Integer getMaxAdultOccupancy() {
        return maxAdultOccupancy;
    }

    /**
     * Sets the value of the maxAdultOccupancy property.
     *
     * @param value allowed object is
     *              {@link Integer }
     */
    public void setMaxAdultOccupancy(Integer value) {
        this.maxAdultOccupancy = value;
    }

    /**
     * Gets the value of the minChildOccupancy property.
     *
     * @return possible object is
     * {@link Integer }
     */
    public Integer getMinChildOccupancy() {
        return minChildOccupancy;
    }

    /**
     * Sets the value of the minChildOccupancy property.
     *
     * @param value allowed object is
     *              {@link Integer }
     */
    public void setMinChildOccupancy(Integer value) {
        this.minChildOccupancy = value;
    }

    /**
     * Gets the value of the maxChildOccupancy property.
     *
     * @return possible object is
     * {@link Integer }
     */
    public Integer getMaxChildOccupancy() {
        return maxChildOccupancy;
    }

    /**
     * Sets the value of the maxChildOccupancy property.
     *
     * @param value allowed object is
     *              {@link Integer }
     */
    public void setMaxChildOccupancy(Integer value) {
        this.maxChildOccupancy = value;
    }

    /**
     * Gets the value of the mediaItems property.
     *
     * @return possible object is
     * {@link MediaItems }
     */
    public MediaItems getMediaItems() {
        return mediaItems;
    }

    /**
     * Sets the value of the mediaItems property.
     *
     * @param value allowed object is
     *              {@link MediaItems }
     */
    public void setMediaItems(MediaItems value) {
        this.mediaItems = value;
    }

    /**
     * Gets the value of the roomCode property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getRoomCode() {
        return roomCode;
    }

    /**
     * Sets the value of the roomCode property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setRoomCode(String value) {
        this.roomCode = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * <p>
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="MediaItem" type="{http://www.thomascook.com/content/common}MediaType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "mediaItem"
    })
    public static class MediaItems {

        @XmlElement(name = "MediaItem")
        List<MediaType> mediaItem;

        /**
         * Gets the value of the mediaItem property.
         * <p>
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the mediaItem property.
         * <p>
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMediaItem().add(newItem);
         * </pre>
         * <p>
         * <p>
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link MediaType }
         */
        public List<MediaType> getMediaItem() {
            if (mediaItem == null) {
                mediaItem = new ArrayList<>();
            }
            return this.mediaItem;
        }

    }

}
