//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.30 at 10:58:29 AM EEST 
//


package com.thomascook.nurvisAdapter.response;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the generated package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
class ObjectFactory {

    private final static QName _Response_QNAME = new QName("", "Response");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ReservationResponseTypeResponse }
     */
    public ReservationResponseTypeResponse createReservationResponseTypeResponse() {
        return new ReservationResponseTypeResponse();
    }

    /**
     * Create an instance of {@link ReservationFahTypeResponse }
     */
    public ReservationFahTypeResponse createReservationFahTypeResponse() {
        return new ReservationFahTypeResponse();
    }

    /**
     * Create an instance of {@link ReservationDetailTypeResponse }
     */
    public ReservationDetailTypeResponse createReservationDetailTypeResponse() {
        return new ReservationDetailTypeResponse();
    }

    /**
     * Create an instance of {@link ReservationErrTypeResponse }
     */
    public ReservationErrTypeResponse createReservationErrTypeResponse() {
        return new ReservationErrTypeResponse();
    }

    /**
     * Create an instance of {@link ReservationWarningTypeResponse }
     */
    public ReservationWarningTypeResponse createReservationWarningTypeResponse() {
        return new ReservationWarningTypeResponse();
    }

    /**
     * Create an instance of {@link ReservationAggregatedCostsTypeResponse }
     */
    public ReservationAggregatedCostsTypeResponse createReservationAggregatedCostsTypeResponse() {
        return new ReservationAggregatedCostsTypeResponse();
    }

    /**
     * Create an instance of {@link ReservationCustomerTypeResponse }
     */
    public ReservationCustomerTypeResponse createReservationCustomerTypeResponse() {
        return new ReservationCustomerTypeResponse();
    }

    /**
     * Create an instance of {@link ReservationFaqTypeResponse }
     */
    public ReservationFaqTypeResponse createReservationFaqTypeResponse() {
        return new ReservationFaqTypeResponse();
    }

    /**
     * Create an instance of {@link ReservationPersonsTypeResponse }
     */
    public ReservationPersonsTypeResponse createReservationPersonsTypeResponse() {
        return new ReservationPersonsTypeResponse();
    }

    /**
     * Create an instance of {@link ReservationFatTypeResponse }
     */
    public ReservationFatTypeResponse createReservationFatTypeResponse() {
        return new ReservationFatTypeResponse();
    }

    /**
     * Create an instance of {@link ReservationAccBalanceTypeResponse }
     */
    public ReservationAccBalanceTypeResponse createReservationAccBalanceTypeResponse() {
        return new ReservationAccBalanceTypeResponse();
    }

    /**
     * Create an instance of {@link ReservationFacTypeResponse }
     */
    public ReservationFacTypeResponse createReservationFacTypeResponse() {
        return new ReservationFacTypeResponse();
    }

    /**
     * Create an instance of {@link ReservationFabTypeResponse }
     */
    public ReservationFabTypeResponse createReservationFabTypeResponse() {
        return new ReservationFabTypeResponse();
    }

    /**
     * Create an instance of {@link ReservationRoomFacilTypeResponse }
     */
    public ReservationRoomFacilTypeResponse createReservationRoomFacilTypeResponse() {
        return new ReservationRoomFacilTypeResponse();
    }

    /**
     * Create an instance of {@link ReservationLegTypeResponse }
     */
    public ReservationLegTypeResponse createReservationLegTypeResponse() {
        return new ReservationLegTypeResponse();
    }

    /**
     * Create an instance of {@link ReservationPurchaseTypeResponse }
     */
    public ReservationPurchaseTypeResponse createReservationPurchaseTypeResponse() {
        return new ReservationPurchaseTypeResponse();
    }

    /**
     * Create an instance of {@link ReservationFeeTypeResponse }
     */
    public ReservationFeeTypeResponse createReservationFeeTypeResponse() {
        return new ReservationFeeTypeResponse();
    }

    /**
     * Create an instance of {@link ReservationDownPayTypeResponse }
     */
    public ReservationDownPayTypeResponse createReservationDownPayTypeResponse() {
        return new ReservationDownPayTypeResponse();
    }

    /**
     * Create an instance of {@link ReservationMandatoryCostsTypeResponse }
     */
    public ReservationMandatoryCostsTypeResponse createReservationMandatoryCostsTypeResponse() {
        return new ReservationMandatoryCostsTypeResponse();
    }

    /**
     * Create an instance of {@link ReservationFapTypeResponse }
     */
    public ReservationFapTypeResponse createReservationFapTypeResponse() {
        return new ReservationFapTypeResponse();
    }

    /**
     * Create an instance of {@link ReservationSalesTypeResponse }
     */
    public ReservationSalesTypeResponse createReservationSalesTypeResponse() {
        return new ReservationSalesTypeResponse();
    }

    /**
     * Create an instance of {@link ReservationPdetTypeResponse }
     */
    public ReservationPdetTypeResponse createReservationPdetTypeResponse() {
        return new ReservationPdetTypeResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReservationResponseTypeResponse }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "Response")
    public JAXBElement<ReservationResponseTypeResponse> createResponse(ReservationResponseTypeResponse value) {
        return new JAXBElement<>(_Response_QNAME, ReservationResponseTypeResponse.class, null, value);
    }

}
