//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.30 at 10:58:29 AM EEST 
//


package com.thomascook.nurvisAdapter.response;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * To store bookable information about insurance or extra-service
 * <p>
 * <p>
 * <p>Java class for Reservation-FacType-Response complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="Reservation-FacType-Response">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="StartDate" type="{}DateType"/>
 *         &lt;element name="Duration">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="-?[0-9]+"/>
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Code">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="6"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Status" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="StatusTech" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="TextS" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="80"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="TextSLong" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="80"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Adults" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="-?[0-9]+"/>
 *               &lt;maxLength value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Children" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="-?[0-9]+"/>
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Infants" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="-?[0-9]+"/>
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Persons" type="{}Reservation-PersonsType-Response" minOccurs="0"/>
 *         &lt;element name="Faq" type="{}Reservation-FaqType-Response" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ServiceType" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="1"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="Key">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="1000"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="SegRef" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="-?[0-9]+"/>
 *             &lt;maxLength value="3"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="Delete">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="-?[0-9]+"/>
 *             &lt;maxLength value="1"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="Modify">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="-?[0-9]+"/>
 *             &lt;maxLength value="1"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Reservation-FacType-Response", propOrder = {
        "startDate",
        "duration",
        "code",
        "status",
        "statusTech",
        "textS",
        "textSLong",
        "adults",
        "children",
        "infants",
        "persons",
        "faq"
})
public class ReservationFacTypeResponse {

    @XmlElement(name = "StartDate", required = true)
    private String startDate;
    @XmlElement(name = "Duration", required = true)
    private String duration;
    @XmlElement(name = "Code", required = true)
    private String code;
    @XmlElement(name = "Status")
    private String status;
    @XmlElement(name = "StatusTech")
    private String statusTech;
    @XmlElement(name = "TextS")
    private String textS;
    @XmlElement(name = "TextSLong")
    private String textSLong;
    @XmlElement(name = "Adults")
    private String adults;
    @XmlElement(name = "Children")
    private String children;
    @XmlElement(name = "Infants")
    private String infants;
    @XmlElement(name = "Persons")
    private ReservationPersonsTypeResponse persons;
    @XmlElement(name = "Faq")
    private List<ReservationFaqTypeResponse> faq;
    @XmlAttribute(name = "ServiceType", required = true)
    private String serviceType;
    @XmlAttribute(name = "Key")
    private String key;
    @XmlAttribute(name = "SegRef", required = true)
    private String segRef;
    @XmlAttribute(name = "Delete")
    private String delete;
    @XmlAttribute(name = "Modify")
    private String modify;

    /**
     * Gets the value of the startDate property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setStartDate(String value) {
        this.startDate = value;
    }

    /**
     * Gets the value of the duration property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDuration() {
        return duration;
    }

    /**
     * Sets the value of the duration property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDuration(String value) {
        this.duration = value;
    }

    /**
     * Gets the value of the code property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCode(String value) {
        this.code = value;
    }

    /**
     * Gets the value of the status property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the statusTech property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getStatusTech() {
        return statusTech;
    }

    /**
     * Sets the value of the statusTech property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setStatusTech(String value) {
        this.statusTech = value;
    }

    /**
     * Gets the value of the textS property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getTextS() {
        return textS;
    }

    /**
     * Sets the value of the textS property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setTextS(String value) {
        this.textS = value;
    }

    /**
     * Gets the value of the textSLong property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getTextSLong() {
        return textSLong;
    }

    /**
     * Sets the value of the textSLong property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setTextSLong(String value) {
        this.textSLong = value;
    }

    /**
     * Gets the value of the adults property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getAdults() {
        return adults;
    }

    /**
     * Sets the value of the adults property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAdults(String value) {
        this.adults = value;
    }

    /**
     * Gets the value of the children property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getChildren() {
        return children;
    }

    /**
     * Sets the value of the children property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setChildren(String value) {
        this.children = value;
    }

    /**
     * Gets the value of the infants property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getInfants() {
        return infants;
    }

    /**
     * Sets the value of the infants property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setInfants(String value) {
        this.infants = value;
    }

    /**
     * Gets the value of the persons property.
     *
     * @return possible object is
     * {@link ReservationPersonsTypeResponse }
     */
    public ReservationPersonsTypeResponse getPersons() {
        return persons;
    }

    /**
     * Sets the value of the persons property.
     *
     * @param value allowed object is
     *              {@link ReservationPersonsTypeResponse }
     */
    public void setPersons(ReservationPersonsTypeResponse value) {
        this.persons = value;
    }

    /**
     * Gets the value of the faq property.
     * <p>
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the faq property.
     * <p>
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFaq().add(newItem);
     * </pre>
     * <p>
     * <p>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReservationFaqTypeResponse }
     */
    public List<ReservationFaqTypeResponse> getFaq() {
        if (faq == null) {
            faq = new ArrayList<>();
        }
        return this.faq;
    }

    /**
     * Gets the value of the serviceType property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getServiceType() {
        return serviceType;
    }

    /**
     * Sets the value of the serviceType property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setServiceType(String value) {
        this.serviceType = value;
    }

    /**
     * Gets the value of the key property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getKey() {
        return key;
    }

    /**
     * Sets the value of the key property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setKey(String value) {
        this.key = value;
    }

    /**
     * Gets the value of the segRef property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSegRef() {
        return segRef;
    }

    /**
     * Sets the value of the segRef property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSegRef(String value) {
        this.segRef = value;
    }

    /**
     * Gets the value of the delete property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDelete() {
        return delete;
    }

    /**
     * Sets the value of the delete property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDelete(String value) {
        this.delete = value;
    }

    /**
     * Gets the value of the modify property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getModify() {
        return modify;
    }

    /**
     * Sets the value of the modify property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setModify(String value) {
        this.modify = value;
    }

}
