//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.30 at 10:58:29 AM EEST 
//


package com.thomascook.nurvisAdapter.response;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * To store bookable information about hotel
 * <p>
 * <p>
 * <p>Java class for Reservation-FahType-Response complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="Reservation-FahType-Response">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="StartDate" type="{}DateType"/>
 *         &lt;element name="Duration">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="-?[0-9]+"/>
 *               &lt;maxLength value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Destination" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ExtBookID" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="16"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Product">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="6"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Room">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ExtraBeds" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="-?[0-9]+"/>
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Meal">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ProductName" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="80"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Product_Street" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="46"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Product_Street_Nr" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="8"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Product_Country" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="40"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Product_Post_Code" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="7"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Product_City" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="40"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Status" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="StatusTech" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Adults" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="-?[0-9]+"/>
 *               &lt;maxLength value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Children" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="-?[0-9]+"/>
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Infants" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="-?[0-9]+"/>
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Persons" type="{}Reservation-PersonsType-Response" minOccurs="0"/>
 *         &lt;element name="RoomFacil" type="{}Reservation-RoomFacilType-Response" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Faq" type="{}Reservation-FaqType-Response" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Detail" type="{}Reservation-DetailType-Response" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ServiceType" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="1"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="Key">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="1000"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="SegRef" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="-?[0-9]+"/>
 *             &lt;maxLength value="3"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="Delete">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="-?[0-9]+"/>
 *             &lt;maxLength value="1"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="Modify">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="-?[0-9]+"/>
 *             &lt;maxLength value="1"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Reservation-FahType-Response", propOrder = {
        "startDate",
        "duration",
        "destination",
        "extBookID",
        "product",
        "room",
        "roomDesc",
        "extraBeds",
        "meal",
        "productName",
        "productStreet",
        "productStreetNr",
        "productCountry",
        "productPostCode",
        "productCity",
        "status",
        "statusTech",
        "adults",
        "children",
        "infants",
        "persons",
        "roomFacil",
        "faq",
        "detail"
})
public class ReservationFahTypeResponse {

    @XmlElement(name = "StartDate", required = true)
    private String startDate;
    @XmlElement(name = "Duration", required = true)
    private String duration;
    @XmlElement(name = "Destination")
    private String destination;
    @XmlElement(name = "ExtBookID")
    private String extBookID;
    @XmlElement(name = "Product", required = true)
    private String product;
    @XmlElement(name = "Room", required = true)
    private String room;
    @XmlElement(name = "ExtraBeds")
    private String extraBeds;
    @XmlElement(name = "Meal", required = true)
    private String meal;
    @XmlElement(name = "RoomDesc")
    private String roomDesc;
    @XmlElement(name = "ProductName")
    private String productName;
    @XmlElement(name = "Product_Street")
    private String productStreet;
    @XmlElement(name = "Product_Street_Nr")
    private String productStreetNr;
    @XmlElement(name = "Product_Country")
    private String productCountry;
    @XmlElement(name = "Product_Post_Code")
    private String productPostCode;
    @XmlElement(name = "Product_City")
    private String productCity;
    @XmlElement(name = "Status")
    private String status;
    @XmlElement(name = "StatusTech")
    private String statusTech;
    @XmlElement(name = "Adults")
    private String adults;
    @XmlElement(name = "Children")
    private String children;
    @XmlElement(name = "Infants")
    private String infants;
    @XmlElement(name = "Persons")
    private ReservationPersonsTypeResponse persons;
    @XmlElement(name = "RoomFacil")
    private List<ReservationRoomFacilTypeResponse> roomFacil;
    @XmlElement(name = "Faq")
    private List<ReservationFaqTypeResponse> faq;
    @XmlElement(name = "Detail")
    private List<ReservationDetailTypeResponse> detail;
    @XmlAttribute(name = "ServiceType", required = true)
    private String serviceType;
    @XmlAttribute(name = "Key")
    private String key;
    @XmlAttribute(name = "SegRef", required = true)
    private String segRef;
    @XmlAttribute(name = "Delete")
    private String delete;
    @XmlAttribute(name = "Modify")
    private String modify;

    /**
     * Gets the value of the startDate property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getRoomDesc() {
        return roomDesc;
    }

    /**
     * Sets the value of the startDate property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setRoomDesc(String value) {
        this.roomDesc = value;
    }

    /**
     * Gets the value of the startDate property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setStartDate(String value) {
        this.startDate = value;
    }

    /**
     * Gets the value of the duration property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDuration() {
        return duration;
    }

    /**
     * Sets the value of the duration property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDuration(String value) {
        this.duration = value;
    }

    /**
     * Gets the value of the destination property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDestination() {
        return destination;
    }

    /**
     * Sets the value of the destination property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDestination(String value) {
        this.destination = value;
    }

    /**
     * Gets the value of the extBookID property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getExtBookID() {
        return extBookID;
    }

    /**
     * Sets the value of the extBookID property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setExtBookID(String value) {
        this.extBookID = value;
    }

    /**
     * Gets the value of the product property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getProduct() {
        return product;
    }

    /**
     * Sets the value of the product property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setProduct(String value) {
        this.product = value;
    }

    /**
     * Gets the value of the room property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getRoom() {
        return room;
    }

    /**
     * Sets the value of the room property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setRoom(String value) {
        this.room = value;
    }

    /**
     * Gets the value of the extraBeds property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getExtraBeds() {
        return extraBeds;
    }

    /**
     * Sets the value of the extraBeds property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setExtraBeds(String value) {
        this.extraBeds = value;
    }

    /**
     * Gets the value of the meal property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getMeal() {
        return meal;
    }

    /**
     * Sets the value of the meal property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setMeal(String value) {
        this.meal = value;
    }

    /**
     * Gets the value of the productName property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getProductName() {
        return productName;
    }

    /**
     * Sets the value of the productName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setProductName(String value) {
        this.productName = value;
    }

    /**
     * Gets the value of the productStreet property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getProductStreet() {
        return productStreet;
    }

    /**
     * Sets the value of the productStreet property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setProductStreet(String value) {
        this.productStreet = value;
    }

    /**
     * Gets the value of the productStreetNr property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getProductStreetNr() {
        return productStreetNr;
    }

    /**
     * Sets the value of the productStreetNr property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setProductStreetNr(String value) {
        this.productStreetNr = value;
    }

    /**
     * Gets the value of the productCountry property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getProductCountry() {
        return productCountry;
    }

    /**
     * Sets the value of the productCountry property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setProductCountry(String value) {
        this.productCountry = value;
    }

    /**
     * Gets the value of the productPostCode property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getProductPostCode() {
        return productPostCode;
    }

    /**
     * Sets the value of the productPostCode property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setProductPostCode(String value) {
        this.productPostCode = value;
    }

    /**
     * Gets the value of the productCity property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getProductCity() {
        return productCity;
    }

    /**
     * Sets the value of the productCity property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setProductCity(String value) {
        this.productCity = value;
    }

    /**
     * Gets the value of the status property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the statusTech property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getStatusTech() {
        return statusTech;
    }

    /**
     * Sets the value of the statusTech property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setStatusTech(String value) {
        this.statusTech = value;
    }

    /**
     * Gets the value of the adults property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getAdults() {
        return adults;
    }

    /**
     * Sets the value of the adults property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAdults(String value) {
        this.adults = value;
    }

    /**
     * Gets the value of the children property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getChildren() {
        return children;
    }

    /**
     * Sets the value of the children property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setChildren(String value) {
        this.children = value;
    }

    /**
     * Gets the value of the infants property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getInfants() {
        return infants;
    }

    /**
     * Sets the value of the infants property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setInfants(String value) {
        this.infants = value;
    }

    /**
     * Gets the value of the persons property.
     *
     * @return possible object is
     * {@link ReservationPersonsTypeResponse }
     */
    public ReservationPersonsTypeResponse getPersons() {
        return persons;
    }

    /**
     * Sets the value of the persons property.
     *
     * @param value allowed object is
     *              {@link ReservationPersonsTypeResponse }
     */
    public void setPersons(ReservationPersonsTypeResponse value) {
        this.persons = value;
    }

    /**
     * Gets the value of the roomFacil property.
     * <p>
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the roomFacil property.
     * <p>
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRoomFacil().add(newItem);
     * </pre>
     * <p>
     * <p>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReservationRoomFacilTypeResponse }
     */
    public List<ReservationRoomFacilTypeResponse> getRoomFacil() {
        if (roomFacil == null) {
            roomFacil = new ArrayList<>();
        }
        return this.roomFacil;
    }

    /**
     * Gets the value of the faq property.
     * <p>
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the faq property.
     * <p>
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFaq().add(newItem);
     * </pre>
     * <p>
     * <p>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReservationFaqTypeResponse }
     */
    public List<ReservationFaqTypeResponse> getFaq() {
        if (faq == null) {
            faq = new ArrayList<>();
        }
        return this.faq;
    }

    /**
     * Gets the value of the detail property.
     * <p>
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the detail property.
     * <p>
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDetail().add(newItem);
     * </pre>
     * <p>
     * <p>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReservationDetailTypeResponse }
     */
    public List<ReservationDetailTypeResponse> getDetail() {
        if (detail == null) {
            detail = new ArrayList<>();
        }
        return this.detail;
    }

    /**
     * Gets the value of the serviceType property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getServiceType() {
        return serviceType;
    }

    /**
     * Sets the value of the serviceType property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setServiceType(String value) {
        this.serviceType = value;
    }

    /**
     * Gets the value of the key property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getKey() {
        return key;
    }

    /**
     * Sets the value of the key property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setKey(String value) {
        this.key = value;
    }

    /**
     * Gets the value of the segRef property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSegRef() {
        return segRef;
    }

    /**
     * Sets the value of the segRef property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSegRef(String value) {
        this.segRef = value;
    }

    /**
     * Gets the value of the delete property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDelete() {
        return delete;
    }

    /**
     * Sets the value of the delete property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDelete(String value) {
        this.delete = value;
    }

    /**
     * Gets the value of the modify property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getModify() {
        return modify;
    }

    /**
     * Sets the value of the modify property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setModify(String value) {
        this.modify = value;
    }

}
