//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.30 at 10:58:29 AM EEST 
//


package com.thomascook.nurvisAdapter.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 Preferences
 *             
 * 
 * <p>Java class for Reservation-FaqType-Response complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Reservation-FaqType-Response">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Code">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="TextQ">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="60"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="TextV" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="26"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="TextVLong" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="380"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="Confirmed">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="1"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Reservation-FaqType-Response", propOrder = {
    "code",
    "textQ",
    "textV",
    "textVLong"
})
public class ReservationFaqTypeResponse {

    @XmlElement(name = "Code", required = true)
    protected String code;
    @XmlElement(name = "TextQ", required = true)
    protected String textQ;
    @XmlElement(name = "TextV")
    protected String textV;
    @XmlElement(name = "TextVLong")
    protected String textVLong;
    @XmlAttribute(name = "Confirmed")
    protected String confirmed;

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCode(String value) {
        this.code = value;
    }

    /**
     * Gets the value of the textQ property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextQ() {
        return textQ;
    }

    /**
     * Sets the value of the textQ property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextQ(String value) {
        this.textQ = value;
    }

    /**
     * Gets the value of the textV property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextV() {
        return textV;
    }

    /**
     * Sets the value of the textV property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextV(String value) {
        this.textV = value;
    }

    /**
     * Gets the value of the textVLong property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextVLong() {
        return textVLong;
    }

    /**
     * Sets the value of the textVLong property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextVLong(String value) {
        this.textVLong = value;
    }

    /**
     * Gets the value of the confirmed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConfirmed() {
        return confirmed;
    }

    /**
     * Sets the value of the confirmed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConfirmed(String value) {
        this.confirmed = value;
    }

}
