//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.30 at 10:58:29 AM EEST 
//


package com.thomascook.nurvisAdapter.response;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * Group-element to store a Transport-position
 * <p>
 * <p>
 * <p>Java class for Reservation-FatType-Response complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="Reservation-FatType-Response">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="StartDate" type="{}DateType"/>
 *         &lt;element name="Duration" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="-?[0-9]+"/>
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Dep">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Arr">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Class" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Chain" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="-?[0-9]+"/>
 *               &lt;maxLength value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Carrier" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="FlightNr" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="5"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DepTime" type="{}TimeType" minOccurs="0"/>
 *         &lt;element name="ArrTime" type="{}TimeType" minOccurs="0"/>
 *         &lt;element name="Status">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="StatusTech">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Adults" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="-?[0-9]+"/>
 *               &lt;maxLength value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Children" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="-?[0-9]+"/>
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Infants" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="-?[0-9]+"/>
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="RealDate" type="{}DateType" minOccurs="0"/>
 *         &lt;element name="RealDepAirport" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="RealArrAirport" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="RealDepTerminal" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Persons" type="{}Reservation-PersonsType-Response" minOccurs="0"/>
 *         &lt;element name="Leg" type="{}Reservation-LegType-Response" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Faq" type="{}Reservation-FaqType-Response" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Detail" type="{}Reservation-DetailType-Response" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ServiceType" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="1"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="Key">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="1000"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="SegRef" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="-?[0-9]+"/>
 *             &lt;maxLength value="3"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="Direction">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="1"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Reservation-FatType-Response", propOrder = {
        "startDate",
        "duration",
        "dep",
        "arr",
        "clazz",
        "chain",
        "carrier",
        "flightNr",
        "depTime",
        "arrTime",
        "systemPortal",
        "status",
        "statusTech",
        "adults",
        "children",
        "infants",
        "realDate",
        "realDepAirport",
        "realArrAirport",
        "realDepTerminal",
        "persons",
        "leg",
        "faq",
        "detail"
})
public class ReservationFatTypeResponse {

    @XmlElement(name = "StartDate", required = true)
    private String startDate;
    @XmlElement(name = "Duration")
    private String duration;

    @XmlElement(name = "SystemPortal")
    private String systemPortal;
    @XmlElement(name = "Dep", required = true)
    private String dep;
    @XmlElement(name = "Arr", required = true)
    private String arr;
    @XmlElement(name = "Class")
    private String clazz;
    @XmlElement(name = "Chain")
    private String chain;
    @XmlElement(name = "Carrier")
    private String carrier;
    @XmlElement(name = "FlightNr")
    private String flightNr;
    @XmlElement(name = "DepTime")
    private String depTime;
    @XmlElement(name = "ArrTime")
    private String arrTime;
    @XmlElement(name = "Status", required = true)
    private String status;
    @XmlElement(name = "StatusTech", required = true)
    private String statusTech;
    @XmlElement(name = "Adults")
    private String adults;
    @XmlElement(name = "Children")
    private String children;
    @XmlElement(name = "Infants")
    private String infants;
    @XmlElement(name = "RealDate")
    private String realDate;
    @XmlElement(name = "RealDepAirport")
    private String realDepAirport;
    @XmlElement(name = "RealArrAirport")
    private String realArrAirport;
    @XmlElement(name = "RealDepTerminal")
    private String realDepTerminal;
    @XmlElement(name = "Persons")
    private ReservationPersonsTypeResponse persons;
    @XmlElement(name = "Leg")
    private List<ReservationLegTypeResponse> leg;
    @XmlElement(name = "Faq")
    private List<ReservationFaqTypeResponse> faq;
    @XmlElement(name = "Detail")
    private List<ReservationDetailTypeResponse> detail;
    @XmlAttribute(name = "ServiceType", required = true)
    private String serviceType;
    @XmlAttribute(name = "Key")
    private String key;
    @XmlAttribute(name = "SegRef", required = true)
    private String segRef;
    @XmlAttribute(name = "Direction")
    private String direction;

    /**
     * Gets the value of the startDate property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setStartDate(String value) {
        this.startDate = value;
    }

    /**
     * Gets the value of the duration property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSystemPortal() {
        return systemPortal;
    }

    /**
     * Sets the value of the duration property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSystemPortal(String value) {
        this.systemPortal = value;
    }

    /**
     * Gets the value of the duration property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDuration() {
        return duration;
    }

    /**
     * Sets the value of the duration property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDuration(String value) {
        this.duration = value;
    }

    /**
     * Gets the value of the dep property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDep() {
        return dep;
    }

    /**
     * Sets the value of the dep property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDep(String value) {
        this.dep = value;
    }

    /**
     * Gets the value of the arr property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getArr() {
        return arr;
    }

    /**
     * Sets the value of the arr property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setArr(String value) {
        this.arr = value;
    }

    /**
     * Gets the value of the clazz property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getClazz() {
        return clazz;
    }

    /**
     * Sets the value of the clazz property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setClazz(String value) {
        this.clazz = value;
    }

    /**
     * Gets the value of the chain property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getChain() {
        return chain;
    }

    /**
     * Sets the value of the chain property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setChain(String value) {
        this.chain = value;
    }

    /**
     * Gets the value of the carrier property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCarrier() {
        return carrier;
    }

    /**
     * Sets the value of the carrier property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCarrier(String value) {
        this.carrier = value;
    }

    /**
     * Gets the value of the flightNr property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFlightNr() {
        return flightNr;
    }

    /**
     * Sets the value of the flightNr property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFlightNr(String value) {
        this.flightNr = value;
    }

    /**
     * Gets the value of the depTime property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDepTime() {
        return depTime;
    }

    /**
     * Sets the value of the depTime property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDepTime(String value) {
        this.depTime = value;
    }

    /**
     * Gets the value of the arrTime property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getArrTime() {
        return arrTime;
    }

    /**
     * Sets the value of the arrTime property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setArrTime(String value) {
        this.arrTime = value;
    }

    /**
     * Gets the value of the status property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the statusTech property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getStatusTech() {
        return statusTech;
    }

    /**
     * Sets the value of the statusTech property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setStatusTech(String value) {
        this.statusTech = value;
    }

    /**
     * Gets the value of the adults property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getAdults() {
        return adults;
    }

    /**
     * Sets the value of the adults property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAdults(String value) {
        this.adults = value;
    }

    /**
     * Gets the value of the children property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getChildren() {
        return children;
    }

    /**
     * Sets the value of the children property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setChildren(String value) {
        this.children = value;
    }

    /**
     * Gets the value of the infants property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getInfants() {
        return infants;
    }

    /**
     * Sets the value of the infants property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setInfants(String value) {
        this.infants = value;
    }

    /**
     * Gets the value of the realDate property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getRealDate() {
        return realDate;
    }

    /**
     * Sets the value of the realDate property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setRealDate(String value) {
        this.realDate = value;
    }

    /**
     * Gets the value of the realDepAirport property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getRealDepAirport() {
        return realDepAirport;
    }

    /**
     * Sets the value of the realDepAirport property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setRealDepAirport(String value) {
        this.realDepAirport = value;
    }

    /**
     * Gets the value of the realArrAirport property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getRealArrAirport() {
        return realArrAirport;
    }

    /**
     * Sets the value of the realArrAirport property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setRealArrAirport(String value) {
        this.realArrAirport = value;
    }

    /**
     * Gets the value of the realDepTerminal property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getRealDepTerminal() {
        return realDepTerminal;
    }

    /**
     * Sets the value of the realDepTerminal property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setRealDepTerminal(String value) {
        this.realDepTerminal = value;
    }

    /**
     * Gets the value of the persons property.
     *
     * @return possible object is
     * {@link ReservationPersonsTypeResponse }
     */
    public ReservationPersonsTypeResponse getPersons() {
        return persons;
    }

    /**
     * Sets the value of the persons property.
     *
     * @param value allowed object is
     *              {@link ReservationPersonsTypeResponse }
     */
    public void setPersons(ReservationPersonsTypeResponse value) {
        this.persons = value;
    }

    /**
     * Gets the value of the leg property.
     * <p>
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the leg property.
     * <p>
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLeg().add(newItem);
     * </pre>
     * <p>
     * <p>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReservationLegTypeResponse }
     */
    public List<ReservationLegTypeResponse> getLeg() {
        if (leg == null) {
            leg = new ArrayList<>();
        }
        return this.leg;
    }

    /**
     * Gets the value of the faq property.
     * <p>
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the faq property.
     * <p>
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFaq().add(newItem);
     * </pre>
     * <p>
     * <p>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReservationFaqTypeResponse }
     */
    public List<ReservationFaqTypeResponse> getFaq() {
        if (faq == null) {
            faq = new ArrayList<>();
        }
        return this.faq;
    }

    /**
     * Gets the value of the detail property.
     * <p>
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the detail property.
     * <p>
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDetail().add(newItem);
     * </pre>
     * <p>
     * <p>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReservationDetailTypeResponse }
     */
    public List<ReservationDetailTypeResponse> getDetail() {
        if (detail == null) {
            detail = new ArrayList<>();
        }
        return this.detail;
    }

    /**
     * Gets the value of the serviceType property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getServiceType() {
        return serviceType;
    }

    /**
     * Sets the value of the serviceType property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setServiceType(String value) {
        this.serviceType = value;
    }

    /**
     * Gets the value of the key property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getKey() {
        return key;
    }

    /**
     * Sets the value of the key property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setKey(String value) {
        this.key = value;
    }

    /**
     * Gets the value of the segRef property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSegRef() {
        return segRef;
    }

    /**
     * Sets the value of the segRef property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSegRef(String value) {
        this.segRef = value;
    }

    /**
     * Gets the value of the direction property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDirection() {
        return direction;
    }

    /**
     * Sets the value of the direction property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDirection(String value) {
        this.direction = value;
    }

}
