//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.06 at 04:28:34 PM EEST 
//


package com.thomascook.wrAdapter.response;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the com.thomascook.wrAdapter.response package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.thomascook.wrAdapter.response
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FullRetailDownloadResponse }
     */
    public FullRetailDownloadResponse createFullRetailDownloadResponse() {
        return new FullRetailDownloadResponse();
    }

    /**
     * Create an instance of {@link PaxDetails }
     */
    public PaxDetails createPaxDetails() {
        return new PaxDetails();
    }

    /**
     * Create an instance of {@link ContactPersonType }
     */
    public ContactPersonType createContactPersonType() {
        return new ContactPersonType();
    }

    /**
     * Create an instance of {@link SourceType }
     */
    public SourceType createSourceType() {
        return new SourceType();
    }

    /**
     * Create an instance of {@link PaymentDetailType }
     */
    public PaymentDetailType createPaymentDetailType() {
        return new PaymentDetailType();
    }

    /**
     * Create an instance of {@link Memos }
     */
    public Memos createMemos() {
        return new Memos();
    }

    /**
     * Create an instance of {@link PaymentCardType }
     */
    public PaymentCardType createPaymentCardType() {
        return new PaymentCardType();
    }

    /**
     * Create an instance of {@link Deposit }
     */
    public Deposit createDeposit() {
        return new Deposit();
    }

    /**
     * Create an instance of {@link FullRetailDownloadResponse.AssociatedRequest }
     */
    public FullRetailDownloadResponse.AssociatedRequest createFullRetailDownloadResponseAssociatedRequest() {
        return new FullRetailDownloadResponse.AssociatedRequest();
    }

    /**
     * Create an instance of {@link OtherDetails }
     */
    public OtherDetails createOtherDetails() {
        return new OtherDetails();
    }

    /**
     * Create an instance of {@link LeadPax }
     */
    public LeadPax createLeadPax() {
        return new LeadPax();
    }

    /**
     * Create an instance of {@link PaxDetails.Pax }
     */
    public PaxDetails.Pax createPaxDetailsPax() {
        return new PaxDetails.Pax();
    }

    /**
     * Create an instance of {@link PaxBreakdown }
     */
    public PaxBreakdown createPaxBreakdown() {
        return new PaxBreakdown();
    }

    /**
     * Create an instance of {@link Passenger }
     */
    public Passenger createPassenger() {
        return new Passenger();
    }

    /**
     * Create an instance of {@link PaymentFormType }
     */
    public PaymentFormType createPaymentFormType() {
        return new PaymentFormType();
    }

    /**
     * Create an instance of {@link PersonNameType }
     */
    public PersonNameType createPersonNameType() {
        return new PersonNameType();
    }

    /**
     * Create an instance of {@link AddressType }
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link UniqueIDType }
     */
    public UniqueIDType createUniqueIDType() {
        return new UniqueIDType();
    }

    /**
     * Create an instance of {@link CompanyNameType }
     */
    public CompanyNameType createCompanyNameType() {
        return new CompanyNameType();
    }

    /**
     * Create an instance of {@link POSType }
     */
    public POSType createPOSType() {
        return new POSType();
    }

    /**
     * Create an instance of {@link AddressInfoType }
     */
    public AddressInfoType createAddressInfoType() {
        return new AddressInfoType();
    }

    /**
     * Create an instance of {@link ContactPersonType.Telephone }
     */
    public ContactPersonType.Telephone createContactPersonTypeTelephone() {
        return new ContactPersonType.Telephone();
    }

    /**
     * Create an instance of {@link SourceType.RequestorID }
     */
    public SourceType.RequestorID createSourceTypeRequestorID() {
        return new SourceType.RequestorID();
    }

    /**
     * Create an instance of {@link SourceType.Position }
     */
    public SourceType.Position createSourceTypePosition() {
        return new SourceType.Position();
    }

    /**
     * Create an instance of {@link SourceType.BookingChannel }
     */
    public SourceType.BookingChannel createSourceTypeBookingChannel() {
        return new SourceType.BookingChannel();
    }

    /**
     * Create an instance of {@link PaymentDetailType.PaymentAmount }
     */
    public PaymentDetailType.PaymentAmount createPaymentDetailTypePaymentAmount() {
        return new PaymentDetailType.PaymentAmount();
    }

    /**
     * Create an instance of {@link Memos.Memo }
     */
    public Memos.Memo createMemosMemo() {
        return new Memos.Memo();
    }

    /**
     * Create an instance of {@link PaymentCardType.CardIssuerName }
     */
    public PaymentCardType.CardIssuerName createPaymentCardTypeCardIssuerName() {
        return new PaymentCardType.CardIssuerName();
    }

}
