//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.06 at 04:28:34 PM EEST 
//


package com.thomascook.wrAdapter.response;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Infant" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="Child" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="Adult" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="Senior" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "infant",
        "child",
        "adult",
        "senior"
})
@XmlRootElement(name = "PaxBreakdown")
public class PaxBreakdown {

    @XmlElement(name = "Infant")
    protected Integer infant;
    @XmlElement(name = "Child")
    protected Integer child;
    @XmlElement(name = "Adult")
    protected Integer adult;
    @XmlElement(name = "Senior")
    protected Integer senior;

    /**
     * Gets the value of the infant property.
     *
     * @return possible object is
     * {@link Integer }
     */
    public Integer getInfant() {
        return infant;
    }

    /**
     * Sets the value of the infant property.
     *
     * @param value allowed object is
     *              {@link Integer }
     */
    public void setInfant(Integer value) {
        this.infant = value;
    }

    /**
     * Gets the value of the child property.
     *
     * @return possible object is
     * {@link Integer }
     */
    public Integer getChild() {
        return child;
    }

    /**
     * Sets the value of the child property.
     *
     * @param value allowed object is
     *              {@link Integer }
     */
    public void setChild(Integer value) {
        this.child = value;
    }

    /**
     * Gets the value of the adult property.
     *
     * @return possible object is
     * {@link Integer }
     */
    public Integer getAdult() {
        return adult;
    }

    /**
     * Sets the value of the adult property.
     *
     * @param value allowed object is
     *              {@link Integer }
     */
    public void setAdult(Integer value) {
        this.adult = value;
    }

    /**
     * Gets the value of the senior property.
     *
     * @return possible object is
     * {@link Integer }
     */
    public Integer getSenior() {
        return senior;
    }

    /**
     * Sets the value of the senior property.
     *
     * @param value allowed object is
     *              {@link Integer }
     */
    public void setSenior(Integer value) {
        this.senior = value;
    }

}
